### ISSUE TITLE
Internal compiler error

### ISSUE THREAD

**Issue by gardners** [cc65/cc65#1075]
I've managed to get an internal compiler error using the following sequence:

```
$ git clone https://github.com/gardners/raycaster.git
$ cd raycaster
$ git checkout dff28c33105dcf2848908488d03f0dd4fc35a908
$ make raycaster.prg 
git submodule init
git submodule update
cl65 --config src/tests/vicii.cfg -I src/mega65-libc/cc65/include -O -o raycaster.prg --mapfile raycaster.map RayCaster/RayCasterFixed.c main.c mazegen.c src/mega65-libc/cc65/src/*.c src/mega65-libc/cc65/src/*.s
RayCaster/RayCasterFixed.c(338): Warning: Unreachable code
RayCaster/RayCasterFixed.c(615): Warning: Converting pointer to integer without a cast
RayCaster/RayCasterFixed.c(625): Warning: Converting pointer to integer without a cast
RayCaster/RayCasterFixed.c(633): Warning: Converting pointer to integer without a cast
main.c(171): Warning: Condition is never true
main.c(172): Warning: Condition is never true
src/mega65-libc/cc65/src/conio.c(148): Warning: Control reaches end of non-void function
src/mega65-libc/cc65/src/conio.c(178): Warning: Result of comparison is constant
src/mega65-libc/cc65/src/conio.c(180): Warning: Result of comparison is constant
src/mega65-libc/cc65/src/conio.c(186): Warning: Parameter 'padding' is never used
src/mega65-libc/cc65/src/conio.c(224): Warning: 'g_curAttr' is defined but never used
src/mega65-libc/cc65/src/random.c(41): Internal compiler error:
Code generation messed up: StackPtr is 2, should be 0

Input: (*(unsigned char*)(0xD774))=range>>0;
cl65: Subprocess 'cc65' aborted by signal 6
Makefile:198: recipe for target 'raycaster.prg' failed
make: *** [raycaster.prg] Error 1
paul@F96NG92-L:~/Projects/mega65/raycaster$ cc65 --version
cc65 V2.18 - Git 17c55041
paul@F96NG92-L:~/Projects/mega65/raycaster$ 
```

I'm guessing it is because I am shifting down a 16 or 32 bit value and implicitly selecting the bottom byte to stash.  But this should presumably not confuse the code-generator like this.

**Comment by acqn** [comment]
Minimal:
```c
long rhs;

int main(void)
{
    /* lhs is errorneously treated as an absolute address neglecting its dereference */
    return *(char *)0xD77C + rhs;
}
```

**Comment by gardners** [comment]
Thanks for the quick confirmation.

**Comment by acqn** [comment]
It turns out that there are confusions in the compiler code regarding what E_LOC_ABS means and how it is supposed to be used. Currenlty it is being used to mean various things:
- An absolute memory address that might be made of an integer constant, as a pointer (may be dereferenced).
- An absolute memory address that might be made of an integer constant, as an integer/pointer (must not be dereferenced).
- An integer constant or an absolute address, as an integer.

Judging by it naming ("LOC" + "ABS"), the first should be the original meaning, but in practice the second is used most (not all) of the time. Thare are suspectible instances of ED_IsLocAbs() usage for checking "const-ness" that should arguably replaced with ED_IsConstAbs() even if they were fully following the third kind of meaning mentioned above.

The bug here is one example of the results of the mess above.

**Comment by mrdudz** [comment]
Can you elobarate a bit on what kind of Operations are affected? I'll come up with testcase perhaps :)

**Comment by acqn** [comment]
> 
> 
> Can you elobarate a bit on what kind of Operations are affected? I'll come up with testcase perhaps :)

- E_LOC_ABS: Integer constants cast to pointers.
- E_LOC_EXPR: Mostly arrays and structs. Maybe pointers to them as well.

Note: I haven't found an instance where E_LOC_EXPR causes a problem in the current codebase, but a fix attempt could break them, so testing is needed for it as well.

**Comment by oliverschmidt** [comment]
Fixed with https://github.com/cc65/cc65/pull/1099.
