### ISSUE TITLE
Increased executable size

### ISSUE THREAD

**Issue by ops** [cc65/cc65#1088]
Compiling tgidemo for vic20 results now executable of size 7987 bytes. With older version (410e4502eee98f74d34477b3ce031bfe0f0386df) from "Wed Jul 8 05:55:30 2020 -0400" size is 7884 bytes.

Is this expected behaviour with the recent compiler changes?

**Comment by mrdudz** [comment]
It's bound to happen when the compiler is fixed/changed....

It's just 100 bytes... i'd try to tweak optimization with --codesize

**Comment by oliverschmidt** [comment]
@acqn: Do you have an opinion? Do you consider this a to-be-expected side effect of your fixes? Or is this alarming?

**Comment by acqn** [comment]
It's this one line in samples/tgidemo.c:

```c
Y = (int) (((long) Amp * -_sin (I)) / 256);
```
With **--Ors --codesize 500** (all by the Makefile), the compiler does inlining as much as it can. It replaces the division here with a shift (which got replcaed with a TXA as a futher optimization) since the newly added code size limit for that is "just" 180. The executable is bigger than with the older revision because of the added case for negative dividend. Recall that _long is signed_.

> 
> 
> @acqn: Do you have an opinion? Do you consider this a to-be-expected side effect of your fixes? Or is this alarming?

I suppose this is expected (#169). There have been some optimizations not pushed to upstream yet, which could help with the size issue in future.

**Comment by oliverschmidt** [comment]
@ops: Thanks for noticing.

@acqn: Thanks for the comprehensive and helpful feedback :-)

Closing...
