### ISSUE TITLE
Testing struct member against NULL is broken

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1181]
As hinted in Issue #1179 i was tracking down a compiler bug... i think i nailed it now :) This breaks my menu system in many interesting ways, would be nice to get a fix soonish (and i promise to work through recent issues and PRs and create more tests... :))

First of all, the last working commit is ba48dfe, 21084895 breaks it.

It seems that generally tests for null (eg) in this form are broken:
```
while (struct->member) { .... }
```

In the "working" compiles of my menusystem, the respective code has the test for null inline, eg like this:
```
; if(menu->helpline) {
	ldy     #$07
	jsr     ldaxysp
	ldy     #$02
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	beq     L00AB
```

In the non working compiles it looks like this:
```
; if(menu->helpline) {
;
	ldy     #$07
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	beq     L00AB
```

While this is shorter, and the actual "load" is perhaps correct (i did not check this), the check for NULL randomly fails (because it doesnt actually happen, its pure coincidence it will sometimes appear to work right). This is probably most obvious when the accessed struct member is a 16bit (or even 32bit) type.

I created a testcase... another thing worth noting is that the testcase itself is kindof fragile - "cleaning up" may result in making it "work" (although the code is still wrong).

Also, it seems noteable that the "printf" is always broken too! that looks like a stack issue to me - which may or may not be related.

[menubug.zip](https://github.com/cc65/cc65/files/5071585/menubug.zip)

@acqn: I can perhaps create a better testcase, if you can hint me at what is actually going wrong here and how to test it better :)

**Comment by acqn** [comment]
The cause is that `StructRef` reuses the same `ExprDesc` to load the left hand side with `LoadExpr()`, which always sets the "expression is tested" flag, for holding the `Struct->Field` result without clearing the now-incorrect flag. Adding one line will fix it.

However, what is the"printf borken" issue? Could you elaborate?

**Comment by acqn** [comment]
```c
#include <stdio.h>

struct {
	int a;
} s = { 256 }, *ps = &s;

int main(void)
{
	if (ps->a) {
	} else {
		printf("ERROR: %d", ps->a);
	}
	return ;
}
```

**Comment by mrdudz** [comment]
> However, what is the"printf borken" issue? Could you elaborate?

expected output (compiled with gcc):
```
numitems (expected 7): 7
passed
```
actual output (compiled with cc65)
```
numitems (expected 7): failed
```
ie, printing stops before the %d for some reason

**Comment by acqn** [comment]
I can't reproduce the `printf` problem.

**Comment by mrdudz** [comment]
did you rebuild head (+libraries) and compiled the test with the included makefile?

**Comment by acqn** [comment]
I'll consider that `printf` issue as a separate one.

**Comment by mrdudz** [comment]
> I'll consider that `printf` issue as a separate one, as that sounds like independent to this (at least at the calling site).

I think it's a non issue, ie PEBCAK. Let's see what @oliverschmidt says :=)

**Comment by oliverschmidt** [comment]
> it also works when i use -t c64 on the invocation of both cc65 and cl65 ... @oliverschmidt: isnt that the default anymore? shrug

From all I know -t c64 was never the default for anything but cl65. And in case anybody cares looking at the docs: It's written there as explicit as one can image, doesn't it?

-t sys, --target sys
The default for this option _**is different from the compiler and linker**_, in the case that the option is missing: _**While the other tools (compiler, assembler, and linker) will use the "none"**_ system settings by default, cl65 will use "c64" as a target system by default. That was chosen because most people seem to use cc65 to develop for the C64.

**Comment by oliverschmidt** [comment]
> and i promise to work through recent issues and PRs and create more tests... :)

Thanks in advance :-)

**Comment by mrdudz** [comment]
> From all I know -t c64 was never the default for anything but cl65. And in case anybody cares looking at the docs: It's written there as explicit as one can image, doesn't it?

yeah yeah. PEBCAK :) I blame it on the heat :)

**Comment by oliverschmidt** [comment]
:-)
