### ISSUE TITLE
Erroneous error for K & R function definitions with enum parameters

### ISSUE THREAD

**Issue by jmr** [cc65/cc65#1263]
This gives an error with `--standard c89`, but should be OK:
```c
enum E { I };
extern int f(enum E);
int f(e) 
  enum E e;
{
  return 1;
}
```
```
% cc65 --standard c89 /tmp/func3.c
/tmp/func3.c(5): Error: Conflicting function types for 'f'
/tmp/func3.c(7): Warning: Parameter 'e' is never used
1 errors and 1 warnings generated.
```
This works with gcc, and used to work with cc65.
[gcc godbolt](https://godbolt.org/z/3rsPEz)
[old cc65 godbolt](https://godbolt.org/z/85de6E)

I didn't try to bisect, but maybe one of @acqn's function handling changes broke this.

It would also be nice if the error message said what the compiler thought the conflicting types were.

The line numbers are also a bit strange, since lines 5 and 7 are the opening and closing curly braces, respectively.

**Comment by mrdudz** [comment]
added test to CI

**Comment by acqn** [comment]
The reason why cc65 generates an error on this is that the parameter `e` in the definition of function `f` is "default-promoted" to `int`: https://github.com/cc65/cc65/blob/97a1093ee09f5efd3569fc8bba9c10a55f4cfb36/src/cc65/typecmp.c#L117-L129
which is not the same as the `enum E` type declared in the prototype of `f`.

I am not sure if I got it right or wrong with the standard: (https://port70.net/~nsz/c/c89/c89-draft.html#3.5.4.3)
>
> For two function types to be compatible, both shall specify compatible return types.
> ...
> If one type has a parameter type list and the other type is specified by a function definition that contains a (possibly empty) identifier list, both shall agree in the number of parameters, and the type of each prototype parameter shall be compatible with the type that results from the application of _the default argument promotions_ to the type of the corresponding identifier.

The only place where I can find the definition of _the default argument promotions_ in the standard text is a bit off-rail: (https://port70.net/~nsz/c/c89/c89-draft.html#3.3.2.2)

> If the expression that denotes the called function has a type that does not include a prototype, the integral promotions are performed on each argument and arguments that have type float are promoted to double. These are called _the default argument promotions_.

And in this standard text, `compatible` means `the same`: (https://port70.net/~nsz/c/c89/c89-draft.html#3.1.2.6)
> Two types have compatible type if their types are the same.

So... I think the standard text means that the example code in the OP should fail, and GCC etc. has made a silent extension to the standard to support that. Correct me if I am wrong on this.

**Comment by acqn** [comment]
Actually, I considered about making such cases work when I made the PR for fixing function prototypes, but the existence of the piece of code for the "default argument promotions" made me take a look at the standard text and decide to leave it "broken as a natural result of some fixes".

**Comment by mrdudz** [comment]
mmmh, as far as i understand it, both cases are basically promoted to int, so they are "the same". i am not sure how to interpret the standard here either :)

**Comment by jmr** [comment]
I haven't looked at the standard enough to have an informed opinion. It seems somewhat less likely this is an extension since it still works with `-pedantic`.

**Comment by jmr** [comment]
> And in this standard text, compatible means the same: (https://port70.net/~nsz/c/c89/c89-draft.html#3.1.2.6)

It says, "Two types have compatible type if their types are the same."

Then it goes on, 
>Additional rules for determining whether two types are compatible are described in 3.5.2 for type specifiers, in 3.5.3 for type qualifiers, and in 3.5.4 for declarators.16 Moreover, two structure, union, or enumeration types declared in separate translation units are compatible if they have the same number of members, the same member names, and compatible member types; for two structures, the members shall be in the same order; for two enumerations, the members shall have the same values.

So I think that's "if", not "if and only if". There are more ways for types to be compatible. Being the same is just one way.

#### [3.5.2.2 Enumeration specifiers](https://port70.net/~nsz/c/c89/c89-draft.html#3.5.2.2)

"Each enumerated type shall be compatible with an integer type; the choice of type is implementation-defined."

**Comment by greg-king5** [comment]
> And in this standard text, `compatible` means `the same`: (https://port70.net/~nsz/c/c89/c89-draft.html#3.1.2.6)
>> Two types have compatible type if their types are the same.

Jesse is correct.  That sentence is misleading.  A "cleaner" way of writing it is,
"If two types have the same base type, then they are compatible."

Also, I think that your cited part of https://port70.net/~nsz/c/c89/c89-draft.html#3.5.4.3 applies to only K & R function-definitions that have a parameter without a type declaration.  It applies to
```c
int f(e)
{
  return e;
}
```
I think that it doesn't apply to
```c
int f(e)
  enum E e;
{
  return e;
}
```
In other words,
- the first definition has "an identifier list",
- the second definition actually has "a parameter type list" -- the type merely is in a different place.

**Comment by greg-king5** [comment]
This code, also, fails with the same message:
```c
enum E { I };
extern int f();

int f(e)
  enum E e;
{
  return e;
}
```

**Comment by acqn** [comment]
Wow that's a lot to reply to. So I'll break down into several posts.

The goal is to get to make clear what is the problem and how to resolve that, right? ;)

So let's start with the "old K & R style" topic:

@mrdudz 
> 
> 
> mmmh, as far as i understand it, both cases are basically promoted to int, so they are "the same". i am not sure how to interpret the standard here either :)

No, I don't think so. It reads to me that the prototype form doesn't do that promotion for comparison, but only the "old K & R form" does.


@greg-king5 
> 
> Also, I think that your cited part of https://port70.net/~nsz/c/c89/c89-draft.html#3.5.4.3 applies to only K & R function-definitions that have a parameter without a type declaration. It applies to
> 
> ```c
> int f(e)
> {
>   return e;
> }
> ```
> 
> I think that it doesn't apply to
> 
> ```c
> int f(e)
>   enum E e;
> {
>   return e;
> }
> ```
> 
> In other words,
> 
>     1. the first definition has "an identifier list",
> 
>     2. the second definition actually has "a parameter type list" -- the type merely is in a different place.

There are some statements with an example in the standard text (https://port70.net/~nsz/c/c89/c89-draft.html#3.7.1) that disagree, if I don't misinterpret them:

> quote begins

**Semantics**

The declarator in a function definition specifies the name of the function being defined and the identifiers of its parameters. _If the declarator includes a **parameter type list**, the list also specifies the types of all the parameters; **such a declarator also serves as a function prototype for later calls to the same function in the same translation unit.** If the declarator includes an identifier list, the types of the parameters may be declared in a following declaration list._ Any parameter that is not declared has type int . 

...

**Examples**
```c
         extern int max(int a, int b)
         {
                  return a > b ? a : b;
         }
```
Here extern is the storage-class specifier and int is the type specifier (each of which may be omitted as those are the defaults); max(int a, int b) is the function declarator; and
```c
         { return a > b ? a : b; }
```
is the function body. _The following similar definition uses the **identifier-list form** for the parameter declarations_:
```c
         extern int max(a, b)
         int a, b;
         {
                  return a > b ? a : b;
         }
```
Here int a, b; is the declaration list for the parameters, which may be omitted because those are the defaults. _The difference between these two definitions is that **the first form acts as a prototype declaration** that forces conversion of the arguments of subsequent calls to the function, **whereas the second form may not**._ 

> quote ends

That's to say, the identifier-list form is not a parameter type list, even if the former had all types of the parameters specified.

**Comment by acqn** [comment]
Now the enum type compatibility part:

@jmr 
> 
> 
> > And in this standard text, compatible means the same: (https://port70.net/~nsz/c/c89/c89-draft.html#3.1.2.6)
> 
> It says, "Two types have compatible type if their types are the same."
> 
> Then it goes on,
> 
> > Additional rules for determining whether two types are compatible are described in 3.5.2 for type specifiers, in 3.5.3 for type qualifiers, and in 3.5.4 for declarators.16 Moreover, two structure, union, or enumeration types declared in separate translation units are compatible if they have the same number of members, the same member names, and compatible member types; for two structures, the members shall be in the same order; for two enumerations, the members shall have the same values.
> 
> So I think that's "if", not "if and only if". There are more ways for types to be compatible. Being the same is just one way.
> #### [3.5.2.2 Enumeration specifiers](https://port70.net/~nsz/c/c89/c89-draft.html#3.5.2.2)
> 
> "Each enumerated type shall be compatible with an integer type; the choice of type is implementation-defined."

@greg-king5 
> 
> 
> > And in this standard text, `compatible` means `the same`: (https://port70.net/~nsz/c/c89/c89-draft.html#3.1.2.6)
> > > Two types have compatible type if their types are the same.
> 
> Jesse is correct. That sentence is misleading. A "cleaner" way of writing it is,
> "If two types have the same base type, then they are compatible."

I agree with you. about the compatibility issue of enums. I forgot the funny (**not** /s) bit about enums when I modified the handling of its underlying types: https://godbolt.org/z/zPP6sK

That's to say, yes, an enum type is considered to be compatible with its underlying integer type.

However, you might be aware of the something: https://godbolt.org/z/6Eqn5G

Provided that my interpretion of the function declaration part was right, the example code in the OP _as it is_ should still fail to compile with cc65, as `enum E { I }` normally uses `unsigned char` rather than `int` as its underlying type.

**Comment by acqn** [comment]
@greg-king5
> 
> 
> This code, also, fails with the same message:
> 
> ```c
> enum E { I };
> extern int f();
> 
> int f(e)
>   enum E e;
> {
>   return e;
> }
> ```

I'll take a look into it.

**Comment by mrdudz** [comment]
> Provided that my interpretion of the function declaration part was right, the example code in the OP as it is should still fail to compile with cc65, as enum E { I } normally uses unsigned char rather than int as its underlying type.

that means the test should get moved to test/err ? and the second snippet (gregs) can be added to test/val ? (should compile and pass) once you fixed it? :)

**Comment by acqn** [comment]
@mrdudz It actually depends on what we really want to support in cc65, even with a "silent non-standard-compliant extension".

**Comment by mrdudz** [comment]
sure. as always, i am fine with making such things errors :)

**Comment by jmr** [comment]
I now agree my initial

```
extern int f(enum E);
int f(e) enum E e; { ... }
```

example was wrong because of the bit about the promoted type from [3.5.4.3](https://port70.net/~nsz/c/c89/c89-draft.html#3.5.4.3).  Interestingly, `cc65` likes

```
extern int f(int);
int f(e) enum E e; { ... }
```

but `gcc -std=c89` doesn't. Maybe I'll file a bug with gcc and see what they say.
