### ISSUE TITLE
take LOW and HIGH byte in ASM directive

### ISSUE THREAD

**Issue by sblendorio** [cc65/cc65#1414]
Hi, I should render in ASM-inline a code like this:

    irqvec   = $0314

         ldx #<mouseirq
         ldy #>mouseirq

         php
         sei

         stx irqvec
         sty irqvec+1

         ...
         ...
    mouseirq lda #$00
         ...

How could I translate in ASM directive like this the "ldx/ldy" and "stx/sty" instructions?

    asm("ldx #%?", ?);
    
Thanks in advance

**Comment by oliverschmidt** [comment]
Knowing well that this is for sure not the answer to the question, I "need" to say that I strongly advise not to do this in the first place. Inline assemblers have only a few true use cases:

* There's no real assembler available easily (think e.g.  Visual Studio): But as cc65 generates just ca65 source code this for sure isn't true here.
* Integrating asm source and C source is hard because of a complicated ABI (especially calling conventions and/or function prologs/epilogs): For sure no true for cc65.
* Improving performance by avoiding the function all overhead for each transition between C and asm: Given that it doesn't makes sense to use any C optimization for functions including inline asm, this for sure isn't applicable to cc65.

**Comment by oliverschmidt** [comment]
I guess the code below answers the question.

```
void mouseirq(void)
{
  __asm__("lda #$00");
}

void (*irqvec)(void) = (void(*)(void))0x0314;

void main(void)
{
  __asm__("ldx #<%v", mouseirq);
  __asm__("ldy #>%v", mouseirq);
  __asm__("php");
  __asm__("sei");
  __asm__("stx %v", irqvec);
  __asm__("sty %v+1", irqvec);
}
```

**Comment by greg-king5** [comment]
That code defines `irqvec` as a normal C variable that points to a system location.  But, @sblendorio needs it to _be_ that system location (i.e., use a macro instead of a declaration).
```C
static void mouseirq(void)
{
  __asm__("lda #$00");
// ...
}

#define IRQVEC 0x0314;

void main(void)
{
  __asm__("ldx #<%v", mouseirq);
  __asm__("ldy #>%v", mouseirq);
  __asm__("php");
  __asm__("sei");
  __asm__("stx %w", IRQVEC);
  __asm__("sty %w+1", IRQVEC);
  __asm__("plp");

// ...
}
```
A more C-like version is this:
```C
#include <6502.h>

static void mouseirq(void)
{
  __asm__("lda #$00");
// ...
}

#define irqvec ((void (**)(void))0x0314)

void main(void)
{
  __AX__ = (int)mouseirq;
  __asm__("php");
  SEI();
  *irqvec = (void (*)(void))__AX__;
  __asm__("plp");

// ...
}
```
