### ISSUE TITLE
String Arrays, assigning different values causes program to go into forever loop

### ISSUE THREAD

**Issue by peteym5** [cc65/cc65#1440]
I am trying to set up an array of strings that store temporary messages that display up onto the string however when I attempt to assign a value to the string, the program gets stuck in a loop and does not go onto the new statement,
```c
// Declared at start of program
char *PLAYERMESSAGE[5]

// inside the program
PLAYERMESSAGE(3) = "This causes the program to freeze";
```
I need help with this. Any documentation refers to C++ or C#.

**Comment by Marrin** [comment]
Could you please show a minimal but complete example of what you are doing.  Because that second line doesn't compile.  The compiler errors are „Illegal function call“ and „Assignment to rvalue“.

**Comment by peteym5** [comment]
Need double slashes .... \\\\ comments
I am trying strcpy(PLAYERMESSAGE(3),"This causes the program to freeze\n"); 
Same Result.

**Comment by Marrin** [comment]
You mean // and not \\\\.  And yes, somewhat the same result because there's still the compiler error with the illegal function call.  This doesn't even compile, yet you say there's a problem at runtime.

Please show a minimal but complete, i.e. compilable and runnable, example that shows the problem. If we don't know what you are *actually* doing, we can't really help but just guess what it might be that you are doing wrong.

**Comment by peteym5** [comment]
char PLAYERMESSAGE[5] = {};

void main(void)
  {
      for (N=0;N<5;N++)      
       { PLAYERMESSAGE[N] = ""; }    
  }
  
  PLAYERMESSAGE is a global (public) variable array. 
  
  The problem could be related to some other tests I am doing elsewhere in the program. It is rather large and not easy to post the whole program here.

**Comment by mrdudz** [comment]
That program is simply wrong, you are assigning a pointer to a string literal to a char, and in the last loop iteration that causes a write beyond the last byte of the array

**Comment by Marrin** [comment]
Again this doesn't compile.  This time because `N` is not defined.  And `PLAYERMESSAGE` is now a char array instead of a pointer to char array as in the example lines before.  Seriously, how hard can it be to open a text file, write a small example that compiles without errors and warnings, and then run that to make sure it actually shows the alleged buggy behaviour?

**Comment by oliverschmidt** [comment]
@Marrin: Keep calm. Just follow my example and ignore individuals just asking to be ignored ;-)

**Comment by Marrin** [comment]
No worries, I am calm. :-)

**Comment by greg-king5** [comment]
Go back to your first example; it's almost right.  But, you confused two different programming languages.  The first line has C syntax for arrays.  But, the second line has BASIC syntax for arrays.

Therefore, change the second one from parentheses to brackets.

**Comment by polluks** [comment]
@peteym5 There's no example of string handling in pure C in the whole Internet? Aha.
Anyway I suppose you want five strings, not a five character long string...
