### ISSUE TITLE
Creating a runtime.lib

### ISSUE THREAD

**Issue by NateDogg1232** [cc65/cc65#1545]
I think it'd be beneficial to build a runtime.lib as a part of the build process of cc65's libraries and this is mainly for two reasons:
1. Faster build times
2. Compartmentalization

I feel the usefulness of 1 is self-explanatory so I'll move on to why 2 is useful.
Having the C runtime alone in a library is useful because it removes one of the steps in adding another system, which is to copy the library of another system, and add your own crt0 and other things into it. Also, if you do not want or need the C runtime in your project because you're coding it in assembly, but would still like access to some of the functions and other things from the library, you can just simply omit the runtime.lib when linking.

The reason I'm creating this and not just doing a merge request is because to be quite honest I don't understand the Makefile in `libsrc`

So for some clarification here's the build steps I'm thinking of (using sim6502 as an example):
1. Assemble all the files in `libsrc/runtime` and archive them into `$out/runtime.lib`
    - This step only needs to be done once in the entire build process, which is where the better build times come into play
2. Assemble all the files in `libsrc/sim6502`
3. Package those into `$out/sim6502.lib`
4. Repeat 3 until all different libraries are done

When targeting a specific target, we can just simply include the runtime.lib and the system's .lib file by default, and if people don't want to do that, they can include the system's .lib file without the runtime.lib file.

I'd like to note that I'd be willing to implement this if somebody can explain to me exactly how the existing Makefile works.

**Comment by oliverschmidt** [comment]
First of all, thanks for your interest in contributing to cc65!

However, I don't consider the approach you described above as beneficial and/or desirable. Therefore I wouldn't merge a PR implementing it.

**Comment by NateDogg1232** [comment]
So out of curiosity, why exactly is it not beneficial or desirable just so I know in the future and can learn something from it.

**Comment by polluks** [comment]
@NateDogg1232 I like the idea but what about different CPU types?

**Comment by NateDogg1232** [comment]
Ah you know I didn't really take that into consideration. That being said, does the C runtime optimize on a CPU basis or does it use only the base 6502 instructions?

I also just right now saw a glaring issue in the build process that I proposed so I'll edit that right now.

**Comment by oliverschmidt** [comment]
What you call a "glaring issue" is what I call a carefully chosen design decission. The builds for the different targets share nothing.

And yes, de facto this leads to creating the identical output many times. But the build system doesn't have the information to avoid that. It neither knows abou the CPU, the chars set nor potential ifdef's nor the actual files built in the first place (see VPATH).

And finally, you answered your question (partly) yourself. You don't understand the Makefile in question. It IS hard to understand. It's not appropriate to add more complextity to it without benefit.

Why "without benefit"? Because I don't see the need to remove something from a library in order to play with it or repurpose it in the first place. What isn't needed in the library doesn't hurt anybody. What is wrong in the library can at any point "overridden" by placing a replacement before the library on the linker command line.

**Comment by oliverschmidt** [comment]
It seems save to close this "question"...
