### ISSUE TITLE
Explain How To Participate In The Wiki And Why It Is In A Separate Repository From cc65

### ISSUE THREAD

**Issue by elderling** [cc65/cc65#1569]
Please explain how one participates in the Github Wiki for cc65 in the README.md (Or explain it to me and I'll create a pull request for the change.) Tangentially, why is the Wiki in a repository all by itself instead of associated with the cc65 repository in Github?

**Comment by oliverschmidt** [comment]
For https://github.com/cc65/cc65/blob/master/README.md you can send a pull request.

For https://github.com/cc65/wiki/wiki you can ask me to provide you with write access - ideally with a plan of what you want to contribute.

The reason is that I want the Wiki editors to be a different (in fact larger) group than the code contributors.

**Comment by elderling** [comment]
Understood, thanks!
