### ISSUE TITLE
not defined CLOCKS_PER_SEC on apple2

### ISSUE THREAD

**Issue by RodrigoDornelles** [cc65/cc65#1597]

**Comment by oliverschmidt** [comment]
That's no a bug not a side effect of clock() not being implemented on the Apple II.

A clock() implementation for a stock Apple II is plainly impossible. Sample programs coming with cc65 have to deal with that too, see e.g. https://github.com/cc65/cc65/blob/master/samples/sieve.c#L14-L18

The only thing possible - and since a rather short time actually available - is waiting for the vertical sync, but only for the apple2enh target, not the apple2 target. See https://github.com/cc65/cc65/blob/master/include/apple2enh.h#L119-L120. Please note that it isn't possible to detect with reasonable effort, if the vertical sync is 50Hz or 60Hz.

**Comment by polluks** [comment]
@oliverschmidt Maybe we should add a hint to library.sgml after time() because of this missing C99 feature.

**Comment by oliverschmidt** [comment]
Thanks for the hint - done, see https://github.com/cc65/cc65/commit/f796c260910cf6047623c3c550fa1153f4e839ae
