### ISSUE TITLE
CA65 "Illegal Addressing Mode" Error when using Symbols as Indirect Address

### ISSUE THREAD

**Issue by ProxyPlayerHD** [cc65/cc65#1600]
basically:
```
.import symbol_xyz
LDA ($00)           ; This will Assemble
LDA (symbol_xyz)    ; This won't
```
All i'm trying to do is make a Library with various Serial functions that allows you to specify where the UART/FTDI is located in Memory, so you don't have to re-assemble and re-archive everything when you use it for a different system.
and i can't think of another way to do this, than to use some reserved ZP Locations and having each function use the indirect addressing mode on them.
or can you just define symbols in the main C file and the linker figures it out on it's own that it needs to export them to the library?

**Comment by mrdudz** [comment]
First of all - what CPU is your target?

**Comment by ProxyPlayerHD** [comment]
oh sorry, the 65C02, the original assembly file has ".PC02" in it and the CMD command i use to assemble is:

`CA65 --cpu 65C02 file.s`

**Comment by mrdudz** [comment]
OK, so that is a valid instruction afterall :)

This kind of thing is always tricky in 6502 assemblers - the problem here is that the line is ambiguous. the argument could be an expression in braces, or the braces could indicate indirect addressing - the assembler has no way to tell what is what. So, the workaround often is to use the first thing after the opening brace to tell the two apart: numeric literal after the opening brace indicates indirect addressing, anything else is an expression. I have to admit i dont know how ca65 deals with this, but try

lda (0 + symbol)

or perhaps tell it what addressmode you want by using the prefix

lda (z:symbol)

Whats the error message you are getting?

**Comment by groessler** [comment]
you could use ".importzp symbol_xyz"

**Comment by mrdudz** [comment]
> you could use ".importzp symbol_xyz"

oh damn, yes of course =) coffee time

**Comment by ProxyPlayerHD** [comment]
well that seems to be working as expected, thanks!
i can now make libraries with relocatable Addressess.

**Comment by ProxyPlayerHD** [comment]
actually if i might still add to this one, symbols seem to assume they are 16 bit wide by default.
that's why whenver i try to use a symbol as anything 8 bit, like indirect addressing `LDA (symbol_xyz, X)` or `LDA (symbol_xyz), Y`, or as immediate value like `LDA #symbol_xyz` i always either get a "range error" or "illegal addressing mode" error.

so how would one force a symbol to be 8 bits wide so that it can be used in immediate addressing modes or similar without `importzp`?

**Comment by mrdudz** [comment]
using the z: prefix

**Comment by ProxyPlayerHD** [comment]
oh sorry i was still editing the comment.

how exactly do you use the z prefix anyways? when i use it like you did in the comment above `LDA (z:symbol)` it just gives me a bunch of syntax errors
```
_ftprintc.s:22: Error: Syntax error
_ftprintc.s:22: Error: ')' expected
_ftprintc.s:22: Error: Unexpected trailing garbage characters
```

**Comment by ProxyPlayerHD** [comment]
I still have not figured out how to use the prefixes, or how to declare exportable symbols with specific values within C...
any tips or should i just open a new issue for this?
