### ISSUE TITLE
Atari Lynx target is broken

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1642]
Linking any program for the Atari Lynx target produces a linker error
```
$ cl65 -t lynx -o minimal minimal.c 
lynx/defdir.s:24: Error: Unresolved external '__LOWCODE_SIZE__'
ld65: Error: 1 unresolved external(s) found - cannot create output file
```
I guess at some point the linker config and/or crt0 changed, and it broke. I have zero knowledge about the Lynx and no Emulator installed either - would be nice if someone could have a look.
Once it works, the Makefile(s) in samples and targettest also need to be updated

**Comment by Fabrizio-Caruso** [comment]
@mrdudz 

My currently installed CC65 version can compile and build lynx binaries:
cl65.exe V2.19 - Git c48e821

I have used Handy to emulated the Atari Lynx under Windows:
http://handy.sourceforge.net/

I am not familiar with the details of the Lynx, but I would first try to find the culprit commit and revert or adapt whatever change broke the target. The linker config file is the very same I have in my version (Git c48e821) which has LOWCODE.

I am not familiar with git bisect but that may be the way to go because we only keep one single release.

**Comment by mrdudz** [comment]
One observation: it actually works when using lynx-uploader.cfg or lynx-bll.cfg. it does NOT work with the regular lynx.cfg or lynx-coll.cfg - i dont really understand why that is the case

**Comment by mrdudz** [comment]
skimmed over the commits since then (its not that much since september) and the only one that looked like it could possibly be related is https://github.com/cc65/cc65/commit/325ff9667e924dd80acb24983791d7aa24cd2dad - this should probably use intptr_t instead of size_t - everything else looks totally unrelated. *shrug*
time for bisect indeed. please give it a try :)

**Comment by greg-king5** [comment]
The library didn't break!  It actually never worked for a program that does NOTHING!  (We didn't think that anyone would write such a beast for the Lynx.)

The configure files that work build special debug versions of programs.  The two files that don't work build normal Lynx cartridges.  Those carts have a crude directory.  Each entry has the size of its program.  That size is computed simply by adding the sizes of _every_ segment in the program.  The expression assumes that no segment is missing.

But, a program that's empty doesn't use interrupts.  Therefore, `LOWCODE` isn't linked.  The directory can't be built.  I can change that expression so that unused segments won't break the build process.

**Comment by mrdudz** [comment]
> I can change that expression so that unused segments won't break the build process.

please do!
