### ISSUE TITLE
cc65: Regression in code optimization

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#1652]
The following code is missing an optimization when compiled with the current cc65 version compared to 2.19:

```C
int foo(unsigned char bar, unsigned char baz)
{
    return (bar == 0 || baz == 0);
}
```

This is what cc65 2.19 generates with -Oirs:

```
        jsr     pusha
        ldy     #$01
        ldx     #$00
        lda     (sp),y
        beq     L0005
        lda     (sp,x)
        beq     L0005
        txa
        jmp     incsp2          ; <--
L0005:  tya
        jmp     incsp2
```

And this is what the current version generates:

```
        jsr     pusha
        ldy     #$01
        ldx     #$00
        lda     (sp),y
        beq     L0004
        lda     (sp,x)
        beq     L0004
        txa
        jmp     L0001            ; <--
L0004:  tya
L0001:  jmp     incsp2
```

The pattern is quite common. It is mostly a speed optimization but there are also cases in which the final jump can be removed, in which case it does also shrink the size of the generated code.

Let me know if you need more information.

**Comment by mrdudz** [comment]
> Let me know if you need more information.

If you know how to fix it, that would obviously be very interesting :)

**Comment by mrdudz** [comment]
Well, that would fix this particular case and break others :)

**Comment by rofl0r** [comment]
> Well, that would fix this particular case and break others :)

are you certain ? the linked PR doesn't actually properly explain what it's trying to achieve.

**Comment by kugelfuhr** [comment]
> @kugelfuhr how did you even spot this, btw?

Easy. I looked at the generated code.

> I might try to add some tests for the optimization passes - not sure how exactly that could work right now though :)

sim65 is able to count cycles. So for each test program in your nightly tests, record the number of total cycles it needs to run. Then, flag the test result for manual review if the number of cycles increases. If it decreases, use this number as the new nominal value. Needs some work but technically it's quite easy.

**Comment by mrdudz** [comment]
> Easy. I looked at the generated code.

Yeah well, doesnt sound too easy to me - unless you are specifically searching for some particular detail

> sim65 is able to count cycles. So for each test program in your nightly tests, record the number of total cycles it needs to run. Then, flag the test result for manual review if the number of cycles increases. If it decreases, use this number as the new nominal value. Needs some work but technically it's quite easy.

In theory ... only that we dont count whats best in cycles, but more often in terms of used bytes (which often, but not always, is the faster solution too). And doing it with the (relatively large and non trivial) test programs doesn't seem terribly useful either, it'd lead to wrong positives and missed errors because one thing cancels out another- i'd want more specific tests that test as little as possible, one by one.

**Comment by kugelfuhr** [comment]
> Yeah well, doesnt sound too easy to me - unless you are specifically searching for some particular detail

If you have seen more than just a few lines of generated code, it is quite obvious.

> In theory ... only that we dont count whats best in cycles, but more often in terms of used bytes (which often, but not always, is the faster solution too). And doing it with the (relatively large and non trivial) test programs doesn't seem terribly useful either, it'd lead to wrong positives and missed errors because one thing cancels out another- i'd want more specific tests that test as little as possible, one by one.

Yes. What I described is not perfect but it's easy to implement and will catch quite some cases. But judging from the response to the few bug reports I've submitted, even this simple proposal might be too ambitious. On the other side, while I understand your wish for a perfect solution, pursuing it means that nothing like this will get implemented.

**Comment by mrdudz** [comment]
> What I described is not perfect but it's easy to implement and will catch quite some cases. But judging from the response to the few bug reports I've submitted, even this simple proposal might be too ambitious.

The problem i see with this is simply that there are many situtions that are not an error that will make these tests fail - especially when using the existing tests that werent specifically created to test the optimizer. A simple change that changes the code generated for a common case will potentially break a lot of those tests all at once, requiring to re-record the cycle counts - that doesnt really help, it only creates a lot of manual extra work - and the point of having those automatic tests is to do less work manually, not more :) It's even more impractical because merging a PR requires all tests to pass, which means whoever submits a fix for a codegenerator or optimizer thing would suddenly have to deal with updating a lot of those cycle counts too.

**Comment by mrdudz** [comment]
Been looking a bit into this - and i am even more convinced now that using the cycle count of the existing tests doesnt really help... Not only are there differences in both ways, faster and slower, also they are not seldomly giving wrong impression without closer studying. If we want this kind of tests, they should be isolated better and be more specific. It doesnt help anyone when a couple dozen tests break and you'll have to wast some hour(s) just to find out half of the changes are actually reasonable, and only a few point to actual problems. #1231 for example does indeed make the compiler produce better (shorter and faster code) in many cases, when only -Os or -Oi is used, for example.

In any case, i will push a change to the test makefile that will make them write their output including cycle count into the workdir, and also change the compiler flags to output the sourcelines - which will make it easier to analyze things like this. It'd also indeed be almost trivial to add automatic checking for the cycle count on top. But really, blindly doing it for all existing tests will create too much noise.

I also found a code snippet that results in better code in head with -Osir, will push a testprog later when i am done crawling through all the differences.

**Comment by rofl0r** [comment]
> vs head (this program is faster!)

the only way this can be faster is if the `beq L0002` branch is taken, and the one byte shorter bra instruction happens to not cause a page cross for a one-cycle penalty hit, but if the branch is not taken, bra+jmp will always be 2 cycles slower than just jmp.

> https://github.com/cc65/cc65/pull/1231 for example does indeed make the compiler produce better (shorter and faster code) in many cases, when only -Os or -Oi is used, for example.

did you test pre-1231 repo version vs HEAD or did you test HEAD against HEAD with PR 1231 reverted ? if the former, other codechanges may be responsible for the better code you're seeing.

> It doesnt help anyone when a couple dozen tests break

if implemented like kugelfuhr suggested, tests would only break if a codegen pessimization is introcuded, which is unlikely to happen except if someone is trying to tweak other parts of the codegen.

as for how to implement it practically, i think you could make a dedicated directory test/codegen which has a .cycles file for each .s in there. if the test is run and the cycles measured are bigger than what's in the .cycles file then the test fails, if it's smaller or equal the test passes, and additionally, if it's smaller the .cycles file will be updated with new value. assuming someone tuning the codegen is using git, he now immediately sees which codegen tests have been improved and can check the changed .cycles files in along with his codegen tuning.

**Comment by mrdudz** [comment]
> the only way this can be faster is if the beq L0002 branch is taken, and the one byte shorter bra instruction happens to not cause a page cross for a one-cycle penalty hit, but if the branch is not taken, bra+jmp will always be 2 cycles slower than just jmp.

No :) The point is - it's not faster because of this code snippet - it is other code in the program that is now located at a different address, and somewhere else there is now no more page crossing happening where there was one before. And this will happen with any program that is more than a hand fil lines of code.

> if the former, other codechanges may be responsible for the better code you're seeing.

i only reverted #1231 locally, also partially for a test so i can see what is going on.

> if implemented like kugelfuhr suggested, tests would only break if a codegen pessimization is introcuded, which is unlikely to happen except if someone is trying to tweak other parts of the codegen.

if only. It will break in other cases too. Like a change in some part of the library that is linked into the program. Or as i already observed, simply because of different code placement.

> as for how to implement it practically, i think you could make a dedicated directory test/codegen which has a .cycles file for each .s in there. if the test is run and the cycles measured are bigger than what's in the .cycles file then the test fails, if it's smaller or equal the test passes, 

As said before, this doesnt really work. Cycle count is also a hint at best - improvements in the code generator may result in shorter but slower code too. Changes in the optimizer may improve the -Osi case but make the -Os case worse. Or the other way around (i have seen both today). That means chances are that *any* change in the codegenerator or optimizer would break some of these tests in one way or another. 

> and additionally, if it's smaller the .cycles file will be updated with new value. assuming someone tuning the codegen is using git, he now immediately sees which codegen tests have been improved and can check the changed .cycles files in along with his codegen tuning.

That doesnt work either. As said, i have seen more than one case now where the produced program with the regression in it runs some cycles faster than the one with the proper code in it.

In any case - to make a long story short - i have fixed the problem in the optimizer (by running some stages again later to clean up this regression). Which means the case #1231 improved is still there and improved, and the regression is fixed. Will commit later after a few more tests and cleanup.

cheers :)

**Comment by rofl0r** [comment]
> As said before, this doesnt really work. Cycle count is also a hint at best - improvements in the code generator may result in shorter but slower code too. Changes in the optimizer may improve the -Osi case but make the -Os case worse. 

indeed, one would need to have one cycle count per optimization level.

**Comment by mrdudz** [comment]
So, please test :)

**Comment by mrdudz** [comment]
No feedback for 3 Months, guess it can be closed then.
