### ISSUE TITLE
sim65 html docs dead link

### ISSUE THREAD

**Issue by icepic** [cc65/cc65#1743]
The sim65 page hints at a list of paravirtual calls your program can use, and links to it "below", but that list is missing from the page so the link points to nothing and the list is not to be seen.

https://cc65.github.io/doc/sim65.html#paravirt-internal

**Comment by polluks** [comment]
Pardon?
https://github.com/cc65/cc65/blob/8328bbf51dd5ac9adaa8adea6001afa1a95b3aa9/doc/sim65.sgml#L162
However the last change is strange
````
commit 52695523465cb8bc72a0728b1f5b46ffc3eb2eef
Author: bbbradsmith <bbbradsmith@users.noreply.github.com>
Date:   Thu May 30 15:34:05 2019 -0400

    sim65 common define for paravirt hooks base location
    allows the loaded binary to take up as much space as possible
    restored some documentation of the hooks but without reference to specific location
````

**Comment by icepic** [comment]
Den ons 11 maj 2022 kl 00:15 skrev Stefan ***@***.***>:

> Pardon?
>
> https://github.com/cc65/cc65/blob/8328bbf51dd5ac9adaa8adea6001afa1a95b3aa9/doc/sim65.sgml#L162
> However the last change is strange
>
I went to the published docs and read this text:

file input and output is provided at a lower level by a set of built-in
paravirtualization functions ( see below
<https://cc65.github.io/doc/sim65.html#paravirt-internal>).

where the last two words seem to indicate they would point to a list of
functions, like the ones found in
https://github.com/cc65/cc65/blob/master/src/sim65/paravirt.c
along the lines of SetAX(), PVArgs(), PVExit() and so on.

The link takes you somewhere on that page, but not to "a set of functions".


> commit 52695523465cb8bc72a0728b1f5b46ffc3eb2eef
> Author: bbbradsmith ***@***.***>
> Date:   Thu May 30 15:34:05 2019 -0400
>
>     sim65 common define for paravirt hooks base location
>     allows the loaded binary to take up as much space as possible
>     restored some documentation of the hooks but without reference to specific location
>
> —
>

-- 
May the most significant bit of your life be positive.

**Comment by polluks** [comment]
@bbbradsmith Can you dissolve it?

**Comment by bbbradsmith** [comment]
The link works, it's just not easy to see where it goes because the jump isn't very far and it's at the bottom so there's no scrolling.

I had initially tried to document the specific paravirtual functions of sim65, but at the same time they were being rearranged, and instead I think we decided it was best not to codify their locations in a document, as they could be subject to further change.

So instead, we just to point out that they exist, in case someone was trying to understand how sim65 worked at a lower level. For more internal details of the paravirtual functions, this just gives them a term they can search for in the source code if they need to know things at that level.

.

So, not sure what to recommend. Maybe just delete the "see below" link as it doesn't appear to help, since it unfortunately doesn't scroll or produce a highlight or anything that helps understand what it's actually linking to.

**Comment by mrdudz** [comment]
I am closing this one, as it is not really a bug. Whoever wants to help may consider documenting those functions properly.
