### ISSUE TITLE
[ca65] improve "Illegal addressing mode" error

### ISSUE THREAD

**Issue by jeffythedragonslayer** [cc65/cc65#1758]
I think this error message could be improved:

`Error: Illegal addressing mode`

by giving me a hint about which illegal addressing mode I actually used, and giving a hint about which syntactically closest legal addressing mode I probably meant.  For example, 

`rep %00100000`

could give the error:

`Error: Illegal addressing mode; rep does not support immediate values (did you forget a #?)`

**Comment by bbbradsmith** [comment]
I don't think it's possible to suggest which one you might mean for most cases?

rep/sep are special because they only have an immediate addressing.

In nearly all other cases there's a large number of addressing modes available for an instruction, and I don't think it would be helpful to try and guess, nor would it be helpful to list them all.

For example, this is one that comes up a lot:
```
stx (ptr), Y
```

This addressing mode doesn't exist. Did you mean:
```
stx zp ; almost certainly not
stx zp, Y ; very unlikely, but possible if your error was putting parentheses around an address calculation?
stx abs ; almost certainly not
```

The actual most common need is for something more like:
```
txa
sta (ptr), Y
```

But you can't just suggested to replace code with that. You have to understand that X can't store through a pointer and A can, and in your program you have to make sure A is available for this.

This kind of thing you really can't tell someone what to do in an error message. I think it just requires experience with the 6502.

**Comment by jeffythedragonslayer** [comment]
Around 2011 I remember Visual Studio would often emit pages of cryptic errors on a large codebase if you forgot a ; after a struct or class definition, but eventually it was improved to give much fewer errors and ask if you forgot a semicolon, so that is where I got the idea.  I do think there are some cases like sep/rep where it is safe and easy to guess which addressing mode was intended and suggest that in an error, but it may be more valuable to simply describe which illegal addressing mode the programmer tried to use and say that mnemonic doesn't support it (many newbies may recognize the names of addressing modes but not their syntax).

**Comment by bbbradsmith** [comment]
I don't believe the assembler should try to guess what the user meant to do in this case, even for REP. It's just as likely that a novice user thought REP could operate on a memory address as they missed a #. So, I don't think there's an appropriate "did you mean" for the simplest case of REP, and I definitely don't think there is one for more complex cases of invalid addressing.

I think it is possible and practical to name the specific addressing mode identified in the error. I'd agree that's worth adding.

However, I'm not sure how much utility it would really have for learning. Learning what the addressing modes look like is a prerequisite for programming in assembly. "Illegal addressing mode: indexed indirect" might give slightly more information than "Illegal addressing mode", but if you don't understand what that "indexed indirect" means, you're going to have to learn it anyway.

If you do know what it means, you can normally just parse it on sight, which is why I think it hasn't really been a big deal to leave this information out of the error. Instruction references often have a list of all the forms of that instruction as syntax, where you can quickly scan the column to realize the line you wrote doesn't match any of them:
* http://www.6502.org/tutorials/65c816opcodes.html#6.1.1.3
* http://www.6502.org/tutorials/6502opcodes.html#STA

**Comment by bbbradsmith** [comment]
To explain why it might be hard to give a good error: syntax and addressing mode do not match 1:1. A syntax is given, and the instruction variations are searched for the best valid match.

For example, if the instruction doesn't have a zeropage addressing mode, an absolute addressing mode would be valid with the same syntax.

So, it might be hard to come up with a good error message. What should it look like? Should it spit out a verbose list of possible addressing modes? That's probably not good. I can't really think of a way to do this properly.

It might be that a "good" error would involve a combinatorial explosion of looking at every addressing syntax vs. every instruction, and thinking of a good explanation for each of them. Not sure how practical that is, though.

"Illegal addressing mode" might seem overly concise, but it's usually pretty quick for a programmer to sort out by looking at the problem with some context of intent.

**Comment by mrdudz** [comment]
i'm closing this one for the reasons already given
