### ISSUE TITLE
Smart mode + typo

### ISSUE THREAD

**Issue by jeffythedragonslayer** [cc65/cc65#1772]
https://cc65.github.io/doc/ca65.html#ss11.102 states (bold emphasis mine):

> The command **must** be followed by a '+' or '-' character to switch the option on or off respectively.

Yet + is not in the example:

` .smart                          ; Be smart`

**Comment by spiro-trikaliotis** [comment]
The compiler accepts all three variants:

1. .smart
2. .smart +
3. ,smart -

You can see in src/ca65/pseudo.c that this is intentional:
In DoSmart(), the function SetBoolOption() is used to set or unset the option for smart.

In SetBoolOption(), it tests for:

- "+" sign --> switch on
- "-" sign --> switch off
- Word "ON" --> switch on
- Word "OFF" --> switch off
- without any paramter: switch on

As many functions use SetBoolOption(), it seems that this is true very often. The documentation is wrong (or, at least, it is not complete).

This behaviour was added in commit 53dd513176, which introduced the file src/ca65/pseudo.c. Thus, it seems the behaviour is intentional, adding undocumented options.

**Comment by jeffythedragonslayer** [comment]
Ok.  Can someone please add the doc label to this issue?

**Comment by spiro-trikaliotis** [comment]
JFTR: This also affects:

- .autoimport
- .case
- .debuginfo
- .linecont
- .list
- .smart

**Comment by bbbradsmith** [comment]
Was this labelled bug by mistake?

PR #2077 replaces the word "must" with "can" in relevant places. I assume that should address what this issue is about.

As far as the SetBoolOption idiom, it seems like it would be too much to spell out the whole deal of "you can use + - on off or nothing" on every single one of these, but I did try to give a hint about the variations in #2009 when I documented the added ability for ```.feature``` to be turned on and off.

**Comment by mrdudz** [comment]
> Was this labelled bug by mistake?

Nope - it is a bug, in the documentation :)

**Comment by mrdudz** [comment]
fixed via #2077
