### ISSUE TITLE
Wrongly generated code when passing a function to a function

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1838]
I have to admit i have not seen this before, i have only ever seen function pointers declared as such. I stumbled about this in the test program used to verify the Berkeley softfloat library:
```
#include <stdlib.h>
#include <stdio.h>
 
int bar( int a )
{
//    printf("a = %d\n", a);
    return 12;
}
 
static void foo(int function(int))
{
    /*int n = */function(42);
//    printf("n = %d\n", n);
}
 
int main(int argc, char *argv[])
{
    foo(bar);
    return EXIT_SUCCESS;
}
```

cc65 gets it "almost" right. but not quite:
```
.proc   _bar: near

        jsr     pushax
        ldx     #$00
        lda     #$0C
        jmp     incsp2

.proc   _foo: near

        jsr     pushax
        lda     _function             ; <- compiler is confused here :)
        ldx     _function+1
        jsr     pushax
        ldx     #$00
        lda     #$2A
        pha
        lda     (sp,x)
        sta     jmpvec+1
        ldy     #$01
        lda     (sp),y
        sta     jmpvec+2
        pla
        jsr     jmpvec
        jsr     incsp2
        jmp     incsp2

.proc   _main: near

        lda     #<(_bar)
        ldx     #>(_bar)
        jsr     _foo
        ldx     #$00
        txa
        jmp     incsp4
```

**Comment by spiro-trikaliotis** [comment]
This can be done in an even more complicated way.

[OpenCBM](https://github.com/OpenCBM/OpenCBM) uses it in this way:

(please ignore the #defines CBMAPIDECL and EXTERN):

`include/opencbm-plugin.h: typedef int CBMAPIDECL opencbm_plugin_init_t(void);
`

Then it defines a pointer to it in a struct:

`include/opencbm-plugin.h: opencbm_plugin_init_t * opencbm_plugin_init;
`

Additionally, in order to make sure that the pointer and the actual defined function match, it uses this:

`lib/archlib.h: EXTERN opencbm_plugin_init_t opencbm_plugin_init;
`

Then, the function opencbm_plugin_init is defined elsewhere.
As long as the flle that defines opencbm_plugin_init includes lib/archlib.h beforehand, the compiler will at least warn at compile time of the function if the function pointer does not match the function prototype.

It would be a nice test case to find out if cc65 handles this correctly...

**Comment by mrdudz** [comment]
please make a simple testcase :)
