### ISSUE TITLE
"make test" no longer works with MSYS2 due to asm/listing tests

### ISSUE THREAD

**Issue by bbbradsmith** [cc65/cc65#1990]
I used to be able to run "make test" with MSYS2 but it's no longer viable due to the asm/listing tests that have been added.

This is because ld65 will be ld65.exe on the windows environment, and diff against the log will fail.

This is the first test that fails:
```
diff -u ref/030-assert-success.ld65err2-ref ../../../testwrk/asm/listing/030-assert-success.ld65-err2
```

It expects lines of this form:
```
ld65: Warning: 030-assert-success.s:3: Code not at $0000
```

Instead it gets a .exe on ld65 and fails the comparison:
```
ld65.exe: Warning: 030-assert-success.s:3: Code not at $0000
```

**Comment by spiro-trikaliotis** [comment]
Just to understand it right: The problem is "only" the additional/missing ".exe" in the log files?

Could you send me such a file for testing purposes, so I can compare if there is something else to consider?

**Comment by bbbradsmith** [comment]
I believe that's the only issue. This is the relevant generated file:
[030-assert-success.zip](https://github.com/cc65/cc65/files/10763842/030-assert-success.zip)

**Comment by bbbradsmith** [comment]
Can confirm that if I locally replace ld65: with ld65.exe: in the asm/listing/ref folder files, it will get through all of the listing tests.

**Comment by spiro-trikaliotis** [comment]
I have a thinig to discuss:
I see two possible ways to fix this:

1. Add a new wildcard "EXE" to the isequal tool, so that the .exe suffix can be present or not present, and the tool will accept both. Note, however,  that all reference files have to be adjusted to this, so the "ld65:" prefix must be changed to "ld65<<<#EXE#>>>:" in every file. This is a high effort, especially as this must be done in all future reference files, too. I see high chances that this will be forgotten.
2. Change src/common/cmdline.c, so that the .exe suffix is removed from ProgName in InitCmdLine. This way, all versions will output the same lines, without the .exe suffix. 

Personally, I would prefer #2. Any opinions?

**Comment by spiro-trikaliotis** [comment]
Just to be sure what we are speaking about: Fixing #1 would need this patch at the moment:
[ld65.diff.gz](https://github.com/cc65/cc65/files/10768632/ld65.diff.gz)

**Comment by mrdudz** [comment]
> Change src/common/cmdline.c, so that the .exe suffix is removed from ProgName in InitCmdLine. This way, all versions will output the same lines, without the .exe suffix.

I don't see a good reason for not doing this
