### ISSUE TITLE
cc65: Using floats silently generates wrong code

### ISSUE THREAD

**Issue by kugelfuhr** [cc65/cc65#2021]
The following works without a warning or error and stores zero into p (instead of 3):

```c
void* p = (int)3.0;
```

**Comment by bbbradsmith** [comment]
This is another case I was surprised, because I did not think cc65 supported float constants at all.

When looking into this, I made PR #2073 with several things that should improve the situation. This particular problem was a combination of the float parsing not working properly, and also the constant conversion assuming everything was an int and reading a 0 integer value from the float expression instead of attempting to convert the floating point value. I tried to add a brief not in the document that float constants are usable.

**Comment by bbbradsmith** [comment]
Sorry if this is redundant, but it feels like the PR fixing this may have gotten lost: #2085 

Changes:
* Fixed the broken floating point parsing.
* Allow float constants to convert to int, with a warning if an implicit conversion would lose precision.
* Gives a descriptive error if floating point constant arithmetic is attempted (since it's not supported).
* Adds test cases to demonstrate that things work as expected.
* Documents the compiler's abilities in this matter.

The PR was waiting on a review vs. some in-progress comprehensive floating point support, but I feel the changes are minor and do not really conflict with that work. It's not really adding much, mostly just fixing up what was already there. The main addition was the conversion to int, which is currently allowed by the compiler anyway but silently produces garbage.

**Comment by mrdudz** [comment]
#2085 is merged so this can be closed :)
