### ISSUE TITLE
Recursive macro issue in ca65

### ISSUE THREAD

**Issue by furrykef** [cc65/cc65#228]
I tried modifying one of the push macros in the examples by adding a fourth argument:

    .macro  push    r1, r2, r3, r4
            lda     r1
            pha
    .if     .paramcount > 1
            push    r2, r3, r4
    .endif
    .endmacro

    push 1, 2, 3, 4

While the original three-argument version worked fine, this version fails spectacularly with a ton of error messages about an illegal addressing mode. I have no idea what the problem is.

The .ifblank/.exitmacro equivalent of this macro works fine, by the way; it's only the .paramcount version that doesn't work.

**Comment by greg-king5** [comment]
`.paramcount` cannot be used in recursive macroes because it counts empty (blank) arguments, too.  That example, in the ca65 document, works only because of a bug in .paramcount's implementation (the last argument isn't counted if it's only a comma [`,{}` is counted]).

I will fix that bug.  And, I will fix that document; it won't say that `.paramcount` can be used in recursive macroes.
