### ISSUE TITLE
[Feature Request] Add performance counter readonly register to sim65

### ISSUE THREAD

**Issue by jroweboy** [cc65/cc65#2355]
A feature request for sim65, right now it only supports printing out the cycle count after program execution, but for performance testing, it would be much more handy if you could access the performance counter directly in the executing application.

### Motivation
The challenge with performance testing with sim65 right now is there's no way to filter out any of the driver and setup code. Additionally, even if you have a minimal test driver, there's not a good way to do average performance metrics, or finding the minimum cycle count/maximum cycle count for code that will change over multiple runs.

### Implementation
One way to achieve this without affecting any existing code would be to add a virtual file that the application can open with `open` with a name that is illegal/unlikely for a file to contain. For Linux, its not really possible to have such a filename, as the only illegal characters in filenames are `/` and `\0` which wouldn't work, but its close enough to just use something illegal in windows like `:`.

The cycle counter virtual register can be an unsigned long long, and reading this will return the number of cycles since the start of the application. The bytes returned can be in little endian order, so if the user only needs 16 or 32 bits of counter, they will be able to just read 2 or 4 bytes from the virtual register instead of the full 8 bytes. 

The file descriptor returned can be a negative number. Since this usually indicates error, on the very very very small chance the user has a file named `:cyclecount` that they actually intended to open, the negative return value should tip them off that something is up. The actual number for the FD could be a constant like `-2` to disambiguate with the OS provided error. This is admittedly a bit counter intuitive to return an error, but this way it shouldn't conflict with any real file descriptors on the OS.

Attempting to write to the virtual register will return an error. I don't think its necessary to prevent opening the file with write mode enabled (as it appears to be the default for the open call).

### Example
So with that in mind here's how I could see it working with a small example.

```c
static unsigned long start_count;
static unsigned long end_count;
static unsigned long cycles;
static unsigned long min_cycles, max_cycles, avg_cycles, total_cycles;

int main() {
  // Open the virtual cycle count register
  int perf = open(":cyclecount");
  if (perf >= 0) {
    // Error! Expected virtual register
  }
  
  // Find out how much overhead the reads add.
  read(perf, (void*)&start_count, sizeof(start_count));
  read(perf, (void*)&end_count, sizeof(end_count));
  unsigned int overhead = end_count - start_count;
  
  // Run 100 samples of the task that we are measuring
  for (char i=0; i < 100; i++) {
    read(perf, (void*)&start_count, sizeof(start_count));
    // Do Task
    read(perf, (void*)&end_count, sizeof(end_count));
    // Calculate our perf metrics
    cycles = end_count - start_count - overhead;
    if (cycles < min_cycles) {
      min_cycles = cycles;
    }
    if (cycles > max_cycles) {
      max_cycles = cycles;
    }
    total_cycles += cycles;
  }
  // Finally print out the results
  avg_cycles = total_cycles / 100;
  printf("Estimated cycle count. Min: %ul Max: %ul Avg: %ul", min_cycles, max_cycles, avg_cycles);
}
```

**Comment by mrdudz** [comment]
The idea is good - but implementing it like this seems a bit overkill - I'd really have a "register" for this - we could reserve a couple bytes right before the hardware vectors for this (i was also thinking about putting a debug register there, as required by the VICE test bench, so we can run the CPU tests on sim65)

**Comment by jroweboy** [comment]
I'd like that too, but I was concerned about a few things. If these are acceptable tradeoffs I am fine with either way 

1) backwards compat. If an existing application has code that accessed that address it would break.

2) cc65 seems to not support a 64 bit int type, but the internal counter is 64bit, meaning it could be annoying to handle in c. 

3) you can only move 1 byte of the counter at a time, which makes reading it consistently a pain. As you are reading the counter it will be constantly changing so it will be non trivial to copy the value.

3b) alternatively it could be two registers, one to clear the read latch and freeze the cycle value and one to read one byte at a time. This is probably good enough but maybe a little bit more complex that originally planned.

Lemme know what your thoughts are, thanks for the response!

**Comment by mrdudz** [comment]
I'm not concerned about backwards compatibility at all (and i see sim65 mostly as a tool for testing cc65 anyway)

As for reading the counter, it could be done the same way it works in many I/O chips - eg reading the MSB would latch the value, all subsequent reads read the latched value.

Not sure if 32bit wouldn't be enough for any practical purposes either.... 2^32 cycles is already quite some time. I never needed more than 16bit for anything i did on 8bit machines :)

**Comment by polluks** [comment]
"2^32 cycles is already quite some time"
Indeed, >1 hour :-)

**Comment by clbr** [comment]
Did you see the sim65 profiling PR? Seems like the profiling output would also solve your issue.

**Comment by sidneycadot** [comment]
Chiming in to say that I also would like this feature. Some ideas on the implementation.

* As to backward compatibility, this could be a feature that needs to be enabled explicitly.
* The latching idea is essential to ensure a consistent readout. My vote would be to do this by an explicit write to some address, perhaps any of the addresses of the (read-only) counter?
* There is little reason to limit the counter to a 32-bit value. Applications that want more range can have it; applications that don't can just read to bottom 32 (or 16, or 8) bits.
* To minimize 6502 memory footprint, the entire counter could be implemented in a single address. Write: latch a value; read: fetch the latched counter value, starting at the LSB and continuing to the MSB. The latched register could just shift by one byte upon each read.
* If this is implemented, one might also consider implementing several other counters that are potentially useful, e.g. an instruction counter; an NMI counter; and an IRQ counter.
* One potential difficulty is that the latching/reading sequence is stateful, which means that it would be hard to use this feature both from a regular program and from an interrupt routine, without the interrupt routine messing up of the timer readout of the regular program (if it latches a new timer value at just the wrong time). But this is a pretty far-fetched scenario for a program running in sim65. If we want to solve this, an obvious solution would be to provide multiple counters at different addresses, with independent latches.

**Comment by sidneycadot** [comment]
I've done quite a deep dive into sim65 to see how it works, and to check how this feature could be supported.

The simulator does not currently have any memory-mapped registers (which would be a prime candidate to support this feature). That could be changed, but at a cost: For each memory access, a check would need to be done if the memory access targets hardware (like a clock cycle timer) or regular memory. This would impact the performance of the simulator, though probably not by much.

Another possible implementation is through the "paravirtualization" functionality already present in sim65. Currently, this is used, for example, to provide file access from within sim65 to files in the host file system, and some other things, such as passing command line arguments into sim65, and allowing sin65 to pass an exit code to the outside (host) world.

A good option would be to add one (or a few) "paravirtualization" hooks to allow sim65 to access the clock cycle counter. I would propose an interface such as this:
```
; Configure the timer address.
; This would need to be called once, before using timers.
; The address needs to be in RAM, and will need to hold 8 bytes.
; The jsr will return after precisely 6 clock cycles (the cost of a JSR, nothing more).

      lda #<TIMADDR
      lda #>TIMADDR
      jsr ParaVirt_SetClockCounterAddress

; Now if we want to use the timer, just do a JSR to ParaVirt_CaptureClockCounter.
; This will write the 64-bit counter into TIMADDR (LSB) to TIMADDR+7 (MSB).
; This jsr will also return after precisely 6 clock cycles (the cost of the JSR, nothing more).

    jsr ParaVirt_CaptureClockCounter
 ```

This is a usable interface. It's not as pretty as a memory-mapped interface would be I think, but it is easier to implement, and has very little if any performance implications for the simulator, because the paravirtualization stuff is already in the simulator.

Opinions?

**Comment by sidneycadot** [comment]
> We could reserve a couple bytes right before the hardware vectors for this

Well that's where the paravirtualization machinery lives as well. If we're going to have memory-mapped registers, it may be a nice idea to have those in 0xff00..0xff7f, with 0xff90..0xffff reserved for paravirtualization and the usual hardware NMI/RESET/IRQ vectors.

**Comment by mrdudz** [comment]
I'd prefer a memory mapped solutions - it's more "natural" to deal with IMHO

And i just stumbled about some tests in the VICE testbench that run longer than 2^32 cycles :) So exposing all 8 bytes of the counter is probably a good idea anyway.

**Comment by sidneycadot** [comment]
I also think it's more natural to have a memory-mapped interface, but it's a bit more work, since this would be the first memory-mapped thing in the sim6502.

And there's the disadvantage that we'll take a small penalty from now on, on each memory access, since we'll have to check if the access goes to RAM or a (simulated) hardware register, whereas now it can just assume every read/write is to RAM.

Then there's the matter of where we put it.

Looking at sim6502.cfg, the memory map of the sim6502 target is currently like this:

![image](https://github.com/user-attachments/assets/8140d8de-e888-4148-84b5-34398a807cf4)

My proposal would be to reserve the last 64 bytes of page $ff for "system-level stuff", including the 6502 vectors, the paravirtualization target addresses, and, now, to also reserve a space of 32 addresses there as "registers", of which the new CPUCLOCKS timer will occupy one address.

![image](https://github.com/user-attachments/assets/09cae4ca-184c-4195-8d91-6570f5d016e5)

My proposed interface for the address CPUCLOCKS, residing somewhere in the $FFC0..$FFDF region, would be this.

Store operation: copies the current 64-bit clock cycle counter to a 64-bit background register. This takes a snapshot of the 64-bit clock at a well-defined instant. The clock itself can then proceed normally as ever.

Load operation: fetch the current LSB of the counter background register, and shift the background register to the right by 8 bits (shifting in zeros).

Usage examples:

```
        ; Example 1: Load lowest 8 bit of 64-bit clock into the A register.
        
        sta CPUCLOCKS     ; The value is not really stored; this triggers a copy of the current clock value to the background register.
        lda CPUCLOCKS     ; Read just bits 0..7 of the clock, ignore the rest.
        
        ; Example 2: Load lowest 16 bits of th 64-bit clock into the A,X registers.
        
        sta CPUCLOCKS   ; Freeze clock
        lda CPUCLOCKS   ; Load bits 0..7
        ldx CPUCLOCKS   ; Load bits 8..15
        
        ; Example 3: Copy snapshot of full 64-bits of clock to memory.
        
        .data
MEMCLOCK: .res 8

        .code

        sta CPUCLOCKS   ; Freeze clock
        ldx #0                  ; Copy 8 bytes of clock snapshot, LSB to MSB.
@loop: lda CPUCLOCKS
        sta MEMCLOCK,x
        inx
        cpx #8
        bne @loop
```

I could implement this, or something similar, quite easily at this point.

**Comment by mrdudz** [comment]
I'd just reserve the entire last page... and map all 8 bytes into memory space. No point in making it more complicated than it has to be, just for saving a few bytes.

**Comment by sidneycadot** [comment]
The advantage of using just 1 byte would be that it would be less expensive to have other counters in the future, such as:
- instructions processed.
- IRQs processed.
- NMIs processed.

The advantage of having this as 8 separate bytes would be that it's a bit easier to access this from C, since you can just do

uint32 counter = *(uint32_t *)CPUCLOCKS;

It's a matter of taste, mostly. I don't care a lot; having 8 bytes is fine by me.

Do you agree with the "latching" idea (i.e., executa a store to freeze, before access)?

**Comment by mrdudz** [comment]
> Do you agree with the "latching" idea (i.e., executa a store to freeze, before access)?

This is a bit tricky maybe. Of course latching (one way or another) is needed - what exactly would be the best way to implement, i am not sure. Ideally there is a clear "stop" and a clear "continue" condition, which still works with whatever code would be produced by the C compiler (which indeed would be the main reason for mapping the whole 8 bytes). Eg i don't think we can rely on a particular access order. mmmh

**Comment by sidneycadot** [comment]
If you don't want to do an explicit latch, I think the only option would be to latch on reading from the LSB (to accommodate the obvious usecases that only need the low 8, 16, or 32 bits, as well as usecases that read all 64 bits).

But then you depend on the C compiler's reading order, which I don't think is guaranteed.

**Comment by mrdudz** [comment]
I am a bit reluctant with this store-to-latch idea.... because, maybe we want to actually write this register, so we can reset it before measuring.

What about an extra location that will latch the register on any access? (not sure if this could even be "latch ALL counters now")

**Comment by sidneycadot** [comment]
>  because, maybe we want to actually write this register, so we can reset it before measuring.

Can you give me a use case for writing to the counter, that would not be as easily achieved by two reads and a subtraction?

If it's an API thing, it would be trivial to implement a reset_timer() function that reads the current counter value and stores it to a private variable as a reference time, and a read_timer() that reads the current counter and substracts the previously stored reference counter. The advantage of that solution is that it doesn't require low-level support, it can be implemented at the library or application level with just a read-only counter provided by the (simulated) hardware. I prefer to keep low-level stuff minimalistic.

There's a few more disadvantages of a counter that takes writes. A counter that allows writing needs to be maintained/updated independently of the (already available) 64-bits clock-cycle counter. You have to think about the cycle cost of two operations (store and load) rather than one. Will the store take as many cycles as the load? What clock cycle does the counter start counting after the store? Or do we also want to latch stores?

In case of a multi-byte counter (which we want), I think that writing to the counter will also require stop/start functionality of the counter, to be able to be precise about the moment where the new value starts to count.

Allowing just reads gives you all the functionality you need (IMO), and it is pretty trivial to implement. Things start to get just... more complicated once you want to support writes. I personally don't like complicated stuff, especially if I don't really see the added value.

Of course, we could make a latch address that's outside of the counter itself. I personally don't see the need but that's because I always try to minimize memory footprints (hence my former proposal to implement the register on precisely one address).

**Comment by mrdudz** [comment]
> Can you give me a use case for writing to the counter, that would not be as easily achieved by two reads and a subtraction?

No - I'm just thinking out loud :) But you are right, it probably doesn't make sense.

> Of course, we could make a latch address that's outside of the counter itself.

I don't see this working any other way when we want it to be possible to use C code to read the counter (the compiler can basically generate any access order, including accessing a value more than once)

**Comment by mrdudz** [comment]
What about one byte that selects and latches the counter you want to read?

(cc65 doesnt honour "volatile" btw - and it will be very hard to implement this correctly, due to how 6502 works with its dummy accesses)

**Comment by sidneycadot** [comment]
I'm not a huge fan of making the latch operation depend on a value myself. In basically all circumstances it's most useful to latch all counters simultaneously. I'd rather do a latch-all, and then use a selector register that shows which register is visible in the counter.

My proposed interface, for the sake of discussion, would look something like this:

```
COUNTER_BASE   := $FFC0

COUNTER_RES1   := COUNTER_BASE + 0  ; [__] Reserved. Do not read or write.
COUNTER_RES2   := COUNTER_BASE + 1  ; [__] Reserved. Do not read or write.
COUNTER_RES3   := COUNTER_BASE + 2  ; [__] Reserved. Do not read or write.
COUNTER_RES4   := COUNTER_BASE + 3  ; [__] Reserved. Do not read or write.
COUNTER_RES5   := COUNTER_BASE + 4  ; [__] Reserved. Do not read or write.
COUNTER_RES6   := COUNTER_BASE + 5  ; [__] Reserved. Do not read or write.
COUNTER_SELECT := COUNTER_BASE + 6  ; [RW] Select which counter is visible in COUNTER[0..7]. Reset value: 0.
COUNTER_LATCH  := COUNTER_BASE + 7  ; [_W] Latch all counters simultaneously. All counters read as zero if not latched.
COUNTER        := COUNTER_BASE + 8  ; [R_] 8-byte counter value (LSB first, MSB last).

                ; COUNTER_SELECT values:
                ;     0     clock cycle counter.
                ;     1     instruction counter.
                ;     2     IRQ counter.
                ;     3     NMI counter.
                ;   128     wallclock timer (COUNTER[0..3] == nanoseconds, COUNTER[4..7] == POSIX timestamp [s])
                ;   all other values: reserved.
```

**Comment by sidneycadot** [comment]
There are 6 bytes reserved, not 5.

The counter is 8 bytes. (Says so in the comments).

The reserved bytes are there to top out the entire thing at 16 bytes (which is a nicer number), and to accommodate any future enhancements.

**Comment by mrdudz** [comment]
> The reserved bytes are there to top out the entire thing at 16 bytes (which is a nicer number), and to accommodate any future enhancements.

I don't see a reason to do this - it should be no problem in the future even if the location of these registers change for whatever reason. We should simply provide an .inc file and a matching .h file for them, so you can always build your code with whatever sim65 uses.

**Comment by sidneycadot** [comment]
A more technical reason to carve out a sixteen-address space for the timer functionality is the way I intend to organize this in the implementation.

Upon memory access, I need a test to see if the request is to normal RAM, or to the timer peripheral. A good way to do that would be (for example, with the proposed memory map above):

```
if ((Address & 0xffc0) == 0xffc0)
{
    // Access timing register in the 0xffc0..0xffcf aperture.
}
else
{
    // Access normal RAM.
}
```

Such an AND test is a bit quicker than a test on two boundaries.

This mimics the way address decoding is done in hardware -- it's essentially the same reason why the memory apertures of the hardware chips in the Atari and C64 are a page long, with quite a bit of waste  in terms of address space beyond their actual registers: it's cheap to implement it like that.

An obvious alternative to this would be to carve out the entire page 0xff as a memory area for this kind of stuff. However, the complication there is that 0xfffa..0xffff is where the NMI/RESET/IRQ vectors reside, and we want those in regular RAM. So the "non-RAM aperture" (for the timer and perhaps other stuff in the future) optimally needs to sit somewhere in a contiguous block before that, that is a power of two bytes long.

Will all this make a difference in practice on modern hardware? Hardly. A 10-byte block will cost perhaps a handful of clock cycles for each simulated memory access on the computer running sim65, compared to a using 16-byte block. No biggie.

So just carving out a 10-byte block for now and reserving nothing will work just fine. The tradeoff is between 6 bytes of address space vs a tiny bit of lost sim65 performance. Either choice will work, if you prefer a 10-bytes aperture, we'll do that.

**Comment by sidneycadot** [comment]
Okay I'm preparing the work for this in a branch on my own cc65 fork.

Please have a look to see if this is going in a direction that is workable for everybody.

https://github.com/cc65/cc65/compare/master...sidneycadot:cc65:feature-add-timer

The following stuff needs to be added:

* documentation (no experience with that in CC65, what do I do? Where does it go?)
* tests (same questions)

The following implementation items at least warrant a small bit of discussion:

* can I include inttypes.h for printing a 64-bit unsigned value? It's the right thing todo, but it is a C99-or-newer feature and my impression is that that is frowned upon in these quarters.
* I'm using  clock_gettime() to get a realtime clock value. Will that work on a Windows build? I have no idea, I don't even know what kind of build environment is used for windows.

**Comment by sidneycadot** [comment]
Any thoughts, anybody?

**Comment by mrdudz** [comment]
> can I include inttypes.h for printing a 64-bit unsigned value? It's the right thing todo, but it is a C99-or-newer feature and my impression is that that is frowned upon in these quarters.

please do - but only if stdint.h isnt good enough. A bunch of places should aready use PRIxx stuff for that matter :)

> I'm using clock_gettime() to get a realtime clock value. Will that work on a Windows build? I have no idea, I don't even know what kind of build environment is used for windows.

I'd just try what happens when you do you PR (which will trigger a windows build, i guess).

> It would be possible to replace the (rather ugly, IMO) paravirtualization machinery as currently implemented with a memory mapped interface; writing to a certain addressable register would induce a service request, like open an external file, read/write to it, and anything else you can think of.

I have never looked at this so i can not judge the implementation in either sim65 nor the library - but if it makes things easier to handle AND you convert everything to the new system - go for it

> The IRQ and NMI interrupts of the 6502 are implemented in sim65, but there is really no way to trigger them. We could implement a timed-interrupt generator easily as a peripheral - sort of a virtual CIA or POKEY.

That might be interesting indeed - but i'd keep this for "later" :)

**Comment by sidneycadot** [comment]
I added a draft PR #2577. It works, but some things need to be taken care of before merging to master. Please continue the discussion under that PR, as it relates to the implementation proposed there.

**Comment by sidneycadot** [comment]
Ok the PR was reviewed and is now merged in the master. Sim65 now has a clock cycle counter, instruction counter, and even access to the outside world's wallclock time :)

Until we get a new release with updated documentation, check [the counter peripheral documentation here](https://data.jigsaw.nl/sim65.html#s6).

Closing this issue.

**Comment by mrdudz** [comment]
The updated docs should be online automagically when the GHA is done :)

**Comment by rofl0r** [comment]
> $81: latched wallclock time (split: seconds, nanoseconds) selected.

what about y2k38 problem? 32 bit second counter will overflow then...

**Comment by sidneycadot** [comment]
Nah, it's an unsigned value, so we're good until 2106 :)

**Comment by sidneycadot** [comment]
> The updated docs should be online automagically when the GHA is done :)

Under which URL is that?

If I search google for "cc 65 docs", I am led to https://cc65.github.io/doc/ which is not auto-updated as far as I can tell (?)

**Comment by sidneycadot** [comment]
Okay so indeed the github.io site does update if the snapshot build completes, it was just that the PR merge broke the snapshot build. See #2584.

Pfffff. All this sort of induces the feeling that's brilliantly captured in this video: https://www.youtube.com/watch?v=AbSehcT19u0
