### ISSUE TITLE
Required void

### ISSUE THREAD

**Issue by polluks** [cc65/cc65#245]
<pre>void f();

void f()
{
}

int main()
{
return 0;
}</pre>

cl65 a.c
a.c(4): Error: Conflicting types for `f'

gcc -pedantic -Wall a.c
_Nothing, why is GNU so lazy?_
http://stackoverflow.com/questions/2574089/c-function-prototype-void-f-is-it-recommended

**Comment by fo-fo** [comment]
This seems like a bug in cc65 to me.

I have a feeling it has been discussed before, though, has it?

**Comment by greg-king5** [comment]
Yes.  https://sourceforge.net/p/cc65/mailman/cc65-devel/thread/3534FFB4-8A3B-431C-9CE5-B6ABF1E19872%40email.com/#msg34218394

**Comment by polluks** [comment]
Indeed, maybe this behavior should be officially documented?

**Comment by oliverschmidt** [comment]
As far as I understand (after reading the mail thread referenced by Greg too) I seem to understand that the behavior isn't really to be considered a bug. So we're left with the wish/idea to document it - which I consider an enhancement (to the docs).

**Comment by EtchedPixels** [comment]
Ok so having read the threads IMHO it is a bug because the following valid C fails

extern void foo();
extern void foo(int x);

void foo(int x)
{
  return x;
}

For the general case though yes it's a documentation thing - extern void foo(); isn't sufficient because we have no idea if it's cdecl or fastcall. Making the compiler parse

extern void foo();

as meaning 'I don't know how to call it but it returns void' would fix it correctly (and be just as annoying except you'd get a sane error message). Making it assume extern void foo(); was fastcall would hide it for most cases and only code that did

extern void foo();

void foo(int a, ...) {
...
}

would then error. That's an obscure corner case and would mean almost all code using K&R style would just compile as it used to do.

Guessing it's cdecl is just the wrong way around now the compiler defaults to fastcall.

**Comment by polluks** [comment]
"return x;" is a mistake?

**Comment by polluks** [comment]
`return x;` is a mistake?

At least cc65-intern says:
The default convention is `fastcall`, but this can be changed with
the `--all-cdecl` command line option. If a convention is specified in
the function's declaration, that convention will be used instead.
Variadic functions will always use `cdecl` convention.

**Comment by GeekOnSkates** [comment]
Hey there,

I know this is an old issue, but has there been any resolution?  I have code lke this:

`void my_function();  // no "extern"
// Other code that calls, but does not define, my_function
void my_function() {
    // Nothing in here returns anything.  "return;" is called by itself like that...
}
`
And I get the "conflicting types for my_function" error.  I don't know what makes them conflicting, since the declaration and definition have the same parameters (none) and return type (none), but apparently it is for {reasons}. :)

So is "extern" required?  That wouldn't make a lot of sense, but neither does making all variables global (another quirk I found that is required for the code to compile).  Either way, I'd appreciate any info that may be available on the subject.

**Comment by spiro-trikaliotis** [comment]
In C, the declarations

void my_function();
and 
void my_function(void);

are not identical!

The latter (void my_function(void)) tells the compiler that there are no arguments. The former (void my_function()) tells it that the parameters are not given at this point, but might be later. The function might take no, one, two, or even much more arguments.

This is a relict from the pre-ANSI times.

So, adding the void in the parenthesis might help.

**Comment by oliverschmidt** [comment]
> I know this is an old issue, but has there been any resolution?

If there would be then this issue would be closed.

**Comment by greg-king5** [comment]
Commit a0db846a9772ef82cf7163670e7a2fc109ec4b53 fixes the issue.  "Normal" K&R programs should compile (with warnings about obsolete features).  Also, cc65 should be able to compile programs that have a mixed use of K&R and ANSI styles.

**Comment by oliverschmidt** [comment]
:-))
