### ISSUE TITLE
Wrong definition of INTMAX_MIN

### ISSUE THREAD

**Issue by pmor13** [cc65/cc65#2505]
Compiling this program:
```
#include <stdint.h>
#if INTMAX_MIN
#endif
```
leads to:
```
<source>:2: Error: Missing binary operator
<source>:2: Error: ')' expected
<source>:2: Error: Missing binary operator
```
while it does not violate any syntax rule or constraint.

**Comment by mrdudz** [comment]
Is that with a recent build? That should have been fixed since last Weekend :)

**Comment by kugelfuhr** [comment]
Good find. This has been wrong forever but didn't cause errors until recent changes to the preprocessor.

The problem is in the casts in the `#define` (not only for `INTMAX_MIN`). The standard says in ISO/IEC 9899:1999 (E) 7.18.2.2:

>Each instance of any defined macro shall be replaced by a constant expression suitable for use in #if preprocessing directives, ...

Since the expressions do contain casts, they cannot be evaluated by the preprocessor. This worked some time ago because the preprocessor used the expression evaluation from the compiler which understood casts. When expression evaluation for the preprocessor was rewritten, casts are no longer understood by the preprocessor which causes this error.

**Comment by mrdudz** [comment]
apparently i misunderstood the problem :/
