### ISSUE TITLE
Missing diagnostics "expression is not an integral constant expression"

### ISSUE THREAD

**Issue by pmor13** [cc65/cc65#2507]
Sample code:
```
enum { z = (int)1e100 };
```

Expected diagnostics:
```
expression is not an integral constant expression
```
Actual diagnostics:
```
<nothing>
```

**Comment by kugelfuhr** [comment]
cc65 doesn't officially support floating point so this is probably moot.

**Comment by mrdudz** [comment]
perhaps i should merge that floatingpoint branch... i'm still reluctant because it certainly is still broken in many ways

**Comment by kugelfuhr** [comment]
> perhaps i should merge that floatingpoint branch... i'm still reluctant because it certainly is still broken in many ways

That wouldn't change anything regarding this issue. I didn't look at it further when writing my first answer because of "floats aren't supported anyway". But the report is invalid for more reasons:

First: `1e100` is out of range for any integer supported by cc65 which means that the statement triggers undefined behavior and the compiler can therefore do whatever it likes. See ISO/IEC 9899:1999 (E) 6.3.1.4:
> If the value of the integral part cannot be represented by the integer type, the behavior is undefined.

Second: When the floating point value is changed to something in the range of an integer to avoid the UB, we have to lookup ISO/IEC 9899:1999 (E) 6.6 which reads:

> An integer constant expression (footnote 96) shall have integer type and shall only have operands that are integer constants, enumeration constants, character constants, `sizeof` expressions whose results are integer constants, and floating constants that are the immediate operands of casts. Cast operators in an integer constant expression shall only convert arithmetic types to integer types, except as part of an operand to the `sizeof` operator.

With footnote 96 reading:

> An integer constant expression is used to specify the size of a bit-field member of a structure, the value of an enumeration constant, the size of an array, or the value of a case constant.
 
A floating point value is clearly arithmetic, so a cast from `double` to `int` is exactly what is described in the first  paragraph. And, as you can see from the footnote, the standard says explicitly that this covers specifying an enumeration constant.

So I would say this can be closed. No action required.

**Comment by mrdudz** [comment]
right
