### ISSUE TITLE
Internal compiler error: Code generation messed up: StackPtr is -4, should be -2

### ISSUE THREAD

**Issue by clbr** [cc65/cc65#252]
This file causes cc65 to ICE.

Code generation messed up: StackPtr is -4, should be -2

Input: if (tableType == byU32) { U32* hashTable = (U32*) tableBase; return hashTable[h] + srcBase; }
cl65: Subprocess `cc65' aborted by signal 6

```
# include <stdint.h>
typedef  uint8_t BYTE;
typedef uint16_t U16;
typedef uint32_t U32;
typedef  int32_t S32;

typedef enum { byPtr, byU32, byU16 } tableType_t;

static const BYTE* LZ4_getPositionOnHash(U32 h, void* tableBase, tableType_t tableType, const BYTE* srcBase)
{
    if (tableType == byPtr) { const BYTE** hashTable = (const BYTE**) tableBase; return hashTable[h]; }
    if (tableType == byU32) { U32* hashTable = (U32*) tableBase; return hashTable[h] + srcBase; }
    { U16* hashTable = (U16*) tableBase; return hashTable[h] + srcBase; }   /* default, to ensure a return */
}
```

**Comment by greg-king5** [comment]
Those `return` expressions add an offset and a pointer.  The offset must be scaled (multiplied) by the size of the pointer's target, before being added to the pointer.  Usually, we put the pointer first and the offset second; cc65 can handle that sequence easily.  But, when the offset term is first, cc65 cannot know that it needs to be scaled, until cc65 has compiled the pointer term.

At that point, the offset is on the stack; and, the pointer is in the accumulator.  cc65 must use a runtime subroutine to swap those two numbers.  The problem is that the library does not have a 32-bit swapper.  But, cc65 keeps going, anyway.  It creates code that swaps 16 bits; and, adds 16 bits.  The result is that the high half of a 32-bit offset is left orphaned on the stack.

**Comment by greg-king5** [comment]
After more analysis, I discovered that the bug is less severe than I though it is.  cc65 thinks that the offset is an `int` because the function that should demote it is told about the pointer instead of the offset.  Therefore, it thinks that it does not need to do anything.  (The bug is a single-character typo.)

**Comment by oliverschmidt** [comment]
@clbr: Thanks for the report :-)
