### ISSUE TITLE
sim65 : incorrect clock-cycle count for sta abs,x and sta abs,y instructions.

### ISSUE THREAD

**Issue by sidneycadot** [cc65/cc65#2536]
Hello,

There is a bug in sim65/6502.c, concerning the clock cycle count of at least two instructions.

For store instructions with abs,x and abs,y indexing (at least opcodes 0x99 and 0x9d), a clock cycle is added in case the indexing causes a page crossing, since the STO_OP macro invokes the ADR_##mode macro that increments the Cycles variable by one for the ABSX and ABSY addressing modes.

However this extra cycle should not be added for the store operations (sta abs,x and abs,y). (Note: I am not sure about the behavior of undocumented instructions of this type.)

References I checked, specifically, several websites and Rodney Zacks' book, and a check with a hardware 6502 (a vintage Atari 8-bit computer), confirm that this count should unconditionally be 5 clock cycles for store operations, whether a page boundary is crossed or not.

**Comment by kugelfuhr** [comment]
I would suggest to run the simulator against [a test suite](https://github.com/SingleStepTests/65x02.git) as part of the builtin tests. This is can be automated easily.

**Comment by sidneycadot** [comment]
I agree that it would be good to have that; but it is not quite so easy as it looks on first sight, I'm afraid.

- Number of tests is huge, and sim65 currently provides no way to do this other than one-run-per-testcase.
- Interference of the testcases with the test program itself must be avoided.
- The effect description in those test-cases is in terms of bus-cycles, which is not a level that sim65 works at. It is a bit of a challenge to reconcile the information in the testcases with  the way sim65 works.

**Comment by kugelfuhr** [comment]
It's not done in a few minutes, but I would say you're over complicating the issue. This is one data set from the tests as an example:

```json
    {
        "cycles": [
            [
                45930,
                169,
                "read"
            ],
            [
                45931,
                204,
                "read"
            ]
        ],
        "final": {
            "a": 204,
            "p": 237,
            "pc": 45932,
            "ram": [
                [
                    45930,
                    169
                ],
                [
                    45931,
                    204
                ],
                [
                    45932,
                    33
                ]
            ],
            "s": 172,
            "x": 145,
            "y": 150
        },
        "initial": {
            "a": 67,
            "p": 237,
            "pc": 45930,
            "ram": [
                [
                    45930,
                    169
                ],
                [
                    45931,
                    204
                ],
                [
                    45932,
                    33
                ]
            ],
            "s": 172,
            "x": 145,
            "y": 150
        },
        "name": "a9 cc 21"
    }
```

If you look at the data, the implementation becomes pretty clear:

1. Read in the json file. There are libraries for reading json files, so this shouldn't be too much work.
2. Enable sim65 to execute just one instruction.
3. Loop over all data sets in the json, processing the data as follows:
3a. Setup RAM and registers according to the data in "initial". This should be easy to do.
3b. Execute one instruction.
3c. Compare RAM and registers against the values in "final".
3d. Compare the number of clock cycles for this instruction against the number of entries in "cycles". No need to analyze bus cycles further since sim65 doesn't implement them.

If you get differences in 3c or 3d the test failed, otherwise it succeeded.

There are tests for 6502 including illegals, 65c02 and other 6502 variants. So adding support for the tests would add complete test coverage to sim65.

**Comment by sidneycadot** [comment]
I think you're suggesting a tailor-made tester for sim65's execute-single-instruction function (ExecuteInsn in src/sim65/6502.c), rather than a freestanding test tool that invokes a pre-built sim65. That should indeed be feasible, and addresses the first two of my concerns -- those concerns assumed that you would try to run those tests using a pre-built sim65.

My third concern is void because I missed that the post-instruction RAM content is also available in the final state.

I will think about taking this on, I estimate it's about a day of work.

**Comment by kugelfuhr** [comment]
I think the test capability should be added to sim65 itself. Maybe in a custom version, but having it always available (in the release) would have some advantages. You could for example add an option "--run-test xxx.json" to the simulator that throws it into test mode executing the sequence described in my post above. I don't think that this will interfere with normal operation. It's separate code that sets up RAM&registers, calls the ExecuteInsn function and then evaluates RAM&registers.

A standalone tool calling sim65 for each test case will not work well. If you look at just the 6502 tests you will see that it contains 10000 test cases. Multiply this with 256 opcodes and you will get 2.5 million starts of the simulator if you call it from an external tool to execute just one instruction. Plus another 2.5 million test cases for each one of the other cpus. This will probably take days to finish.

A day might not be enough for a complete implementation since you will run into several non working cases and will have to check if it's a problem with the simulator or the test cases. And then, you will find problems with some instructions failing the tests because of errors and will have to research and maybe fix them. But I think it's definitely worth the effort since it will also ease adding more cpus. There are a lot more tests available for other cpus like the 65816.

**Comment by sidneycadot** [comment]
I made a prototype implementation that works:

https://github.com/sidneycadot/sim65-test-prototype

It does demonstrate the issue with the sta abs,x and sta abs,y instructions which are the bug as reported in this issue.

I will think about whether I want to invest the time to properly do this and get it integrated into sim65. Personally I am not very fond of the idea of adding this to sim65 itself as you suggest, it feels out of place to add a tester for a very specific testsuite into the simulator proper. But that's something that could be discussed.

**Comment by sidneycadot** [comment]
As is, it already shows a bit of usefulness:

```
$ ./sim65_test  65x02/6502/v1/a9.json  | grep -v SUCCESS
testcase file: "65x02/6502/v1/a9.json"
[65x02/6502/v1/a9.json:a9 f0 33] ERROR - A register check failed (expected: 0xf0, sim65: 0x00).
[65x02/6502/v1/a9.json:a9 f0 33] ERROR - P register check failed (expected: 0xa1, sim65: 0x23).
[65x02/6502/v1/a9.json:a9 f0 33] ERROR - PC register check failed (expected: 0x00a9, sim65: 0x10001).
```

So apparently sim65 doesn't handle the weird case where code wraps around from $ffff to $0000. That's a minor bug.

Similar also for the S register it seems, if I test the JSR (0x20) instruction.

**Comment by kugelfuhr** [comment]
> Personally I am not very fond of the idea of adding this to sim65 itself as you suggest, it feels out of place to add a tester for a very specific testsuite into the simulator proper.

The advantage is that someone running into a problem can create a single test case reproducing the problem without the need for an additional application. The test cases are more or less randomly selected. They cover lots of scenarios but aren't complete. So even if all tests pass, there's a chance that users run into problems with an instruction. But this is not my decision.

> As is, it already shows a bit of usefulness:

Nice. 

I would suggest an additional option to initialize the RAM contents with a pattern or similar. You may otherwise run into a situation where the allocated RAM contains correct values by coincidence. The tests do not always initialize the target of a write operation with a value different from the expected one. At least this was the case some time ago.

**Comment by sidneycadot** [comment]
A fundamental problem is to what extent the 65x02 testsuite can be regarded as authoritative.

The test suite has this to say on that:

```
To generate each test set, an implementation is used that:

    conforms to all available documentation, official and third-party;
    passes all other published test sets; and
    has been verified by usage in an emulated machine.
```

The process followed (and the documentation, test sets, software, and hardware used) is otherwise undocumented, as far as I can tell. Each of the three verification methods mentioned is prone to mistakes, and they are not independent sources of truth.

The most trustworthy method would be hardware verification using physical chips, using a documented and reproducible process. For the bug originally reported in this issue, I verified behavior on an Atari, and that test was more convincing to me than anything else could ever be.

**Comment by kugelfuhr** [comment]
> A fundamental problem is to what extent the 65x02 testsuite can be regarded as authoritative.

I don't think that's a fundamental problem. And the question if it's authoritative is more or less irrelevant as long as it's good enough. There's always a chance that a test has a false outcome, so if you have test failure you will have to investigate both sides. I have found a few problems with these tests myself and I'm still a big fan.

The real question is: "Is it useful?" followed by "How is the effort spent / usefulness ratio?"

Both questions have been answered in favor of the test. You have spent a few hours to be able to use it and have already found several problems. Isn't that great? Not to speak about the advantages when making code changes or adding other instructions/cpus.

**Comment by sidneycadot** [comment]
Well, we disagree. A test suite that doesn't explain how its test cases were made or can be reproduced is just bad practice, in my opinion.

Now, when a test against the testsuite points to a problem, I cannot trust it as authoritative; rather, I need to double-check (for example, with a real 6502) what the actual behavior is, and if I trust the testsuite's claimed behavior. That requires substantial work, and that makes the testsuite a lot less valuable.

But it's fine for us to disagree on this.

**Comment by sidneycadot** [comment]
I made a new issue to discuss the sim65-test I made: #2539.

I propose that the discussion here be limited to the direct topic of the incorrect cycle counts in sta abs,x and sta abs,y, and that the broader topic of the test suite is moved to #2339.

**Comment by sidneycadot** [comment]
This issue is superseded by the solution proposed in #2539, which will solve this particular bug as a special case.

I am therefore closing this issue.
