### ISSUE TITLE
Redefined chars for the ATARIXL (mode 1)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#490]
Hi

For my multi-system 8-bit game I am now trying to add redefined chars for all the Atari systems.

I am starting with the ATARIXL wit mode 1 enabled.

When redefining a character by writing first the rom content to ram and then modifying the ram will crash the computer.
I am basically POKE'ing into some high location in RAM where there should be no code.

I wonder whether I need to do something the cfg file.
I have read the cfg manual but for me it remains not clear.
Do I need to change the value of CHARGEN??

**Comment by groessler** [comment]
Do you have a specilal reason to use the "atarixl" target instead of the "atari" target?

"atarixl" is intended for big programs where parts of the program can be loaded below the ROM.

That said, if you still want to use "atarixl", there's no need to copy the chargen data to RAM, since it is already in RAM. Just modify it in-place. Just look at CHBAS to find its address.

**Comment by groessler** [comment]
> That said, if you still want to use "atarixl", there's no need to copy the chargen data to RAM, since it is already in RAM. Just modify it in-place. Just look at CHBAS to find its address.

Sorry, wrong (at least partitally). While during program execution the RAM font is active, for interrupt handling and syscalls, the ROM font is banked in again.

> When redefining a character by writing first the rom content to ram and then modifying the ram will crash the computer.
> I am basically POKE'ing into some high location in RAM where there should be no code.

High RAM locations contain the C stack.

You're better off to define an area for your font in the linker config file. Some hints how to do this can be found in http://cc65.github.io/doc/atari.html#ss11.4 .

**Comment by Fabrizio-Caruso** [comment]
I do not need ATARIXL. I thought ATARIXL meant more recent versions of the ATARI computers.

I would like to use both mode 1 and redefined characters.

Do you have a simple example for the ATARI target with redefined characters and possible mode 1?

**Comment by groessler** [comment]
"atari" target supports 400/800 and the XL/XE line. "atarixl" supports machines of the XL/XE line with at least 64KB.

I suggest to put the memory area for the custom font at the beginning of the program, Doing this you can satisfy the alignment requirements for font data by selecting a proper start adress without wasting bytes due to padding.

A simple change to the default atari.cfg could be:

`--- cc65/cfg/atari.cfg      2017-02-01 18:11:45.489284192 +0100
+++ fontfront.cfg       2017-09-19 15:37:53.818375995 +0200
@@ -22,8 +22,11 @@
 
 # "main program" load chunk
     MAINHDR:    file = %O,               start = $0000, size = $0004;
-    MAIN:       file = %O, define = yes, start = %S,    size = $BC20 - __STACKSIZE__ - __RESERVED_MEMORY__ - %S;
+    MAIN:       file = %O, define = yes, start = %S + $0200,    size = $BC20 - __STACKSIZE__ - __RESERVED_MEMORY__ - %S - $0200;
     TRAILER:    file = %O,               start = $0000, size = $0006;
+
+# font area
+    FONT:       file = "",               start = %S,    size = $0200;
 }
 SEGMENTS {
     ZEROPAGE:  load = ZP,         type = zp;
@@ -42,6 +45,7 @@
     INIT:      load = MAIN,       type = rw,                optional = yes;
     BSS:       load = MAIN,       type = bss, define = yes;
     AUTOSTRT:  load = TRAILER,    type = ro;
+    FONT:      load = FONT,       type = rw,  define = yes, optional = yes;
 }
 FEATURES {
     CONDES: type    = constructor,
`

FONT is the font area, and with the line "define=yes" you can get its address in your program.

To use mode 1, you could use the _graphics() function of the runtime lib. Parameter is like the BASIC version, so to have a mode 1 screen write "_graphics(1+16)". Check the return code!

Alternatively, for mode 1, you could define your own display list. You can see how's that done by looking at libsrc/atari5200/conioscreen.s. Atari5200 uses a mode 1 console.
Display lists have alignment restrictions, too. So probably best is to put them directly after the font area. This way, again, no space is wasted by padding.

**Comment by groessler** [comment]
Ahh, shit, the "insert code" in the editor didn't do the right thing...

**Comment by oliverschmidt** [comment]
> I thought ATARIXL meant more recent versions of the ATARI computers.

http://cc65.github.io/doc/atari.html#s1 says: "Since the atarixl runtime has some limitations, it is recommended to use the atari target unless lack of memory dictates the use of the atarixl target." I think that doesn't leave too much room for misinterpretation ;-))

**Comment by groessler** [comment]
Now as attachment....

[fontfront.diff.txt](https://github.com/cc65/cc65/files/1314484/fontfront.diff.txt)

**Comment by Fabrizio-Caruso** [comment]
THANKS a LOT!

Sorry for missing the recommendation on ATARI.

How do I see the concrete address of the FONT? Through which macro? The FONT macro? _FONT_START?
Can I then use this address to copy the content of the rom, change the pointer to this address and so get the redefined characters?

My game is supposed to run on (nearly) *any* computer and many consoles with any 8 bit CPU (Z80, 6502, 6809) and at least 12k of RAM so I have both an ATARI 5200 and an ATARI mode 1 version. For the ATARI I use mode 1 through the CC65's built-in conio (I need to use an adjusted 20-column coordinate system). I chose this solution because it was fast to implement and runs very smooth (even too fast).
conio.h is my default choice because it is supported in Z88DK and CMOC (for the 6809) and I can use (sort of) the same code.

**Comment by Fabrizio-Caruso** [comment]
@mrdudz, I am adventurous but I want to tackle first the computers which are the primary goal of my ambitious project. I am also porting to consoles whenever it is not too hard. I will look at what you have done as soon as I can.

**Comment by groessler** [comment]
On 09/19/17 16:56, Fabrizio Caruso wrote:
> How do I see the concrete address of the FONT? Through which macro? 
> The FONT macro? _FONT_START?


I've tried it and found out that "define=yes" for a segment only works 
if the segment actually has content. But for memory areas "define=yes" 
works independently of content. So please try this updated config file:

----
--- cc65/cfg/atari.cfg  2017-02-01 18:11:45.489284192 +0100
+++ fontfront.cfg       2017-09-20 00:22:11.543919316 +0200
@@ -22,8 +22,11 @@

  # "main program" load chunk
      MAINHDR:    file = %O,               start = $0000, size = $0004;
-    MAIN:       file = %O, define = yes, start = %S,    size = $BC20 - 
__STACKSIZE__ - __RESERVED_MEMORY__ - %S;
+    MAIN:       file = %O, define = yes, start = %S + $0200, size = 
$BC20 - __STACKSIZE__ - __RESERVED_MEMORY__ - %S - $0200;
      TRAILER:    file = %O,               start = $0000, size = $0006;
+
+# font area
+    FONT:       file = "", define = yes, start = %S,    size = $0200;
  }
  SEGMENTS {
      ZEROPAGE:  load = ZP,         type = zp;
@@ -42,6 +45,7 @@
      INIT:      load = MAIN,       type = rw, optional = yes;
      BSS:       load = MAIN,       type = bss, define = yes;
      AUTOSTRT:  load = TRAILER,    type = ro;
+    FONT:      load = FONT,       type = rw, optional = yes;
  }
  FEATURES {
      CONDES: type    = constructor,
----



> Can I then use this address to copy the content of the rom, change the 
> pointer to this address and so get the redefined characters?


Yes, you can use for example

----
extern char _FONT_START__[];
unsigned char *CHBAS = (unsigned char *)0x2f4;
...
memcpy(_FONT_START__, (void *)0xE000, 512);
/* modify your font at _FONT_START__, etc, then set the new font: */
*CHBAS = ((int)_FONT_START__ >> 8);  /* enable the new font */
----

to copy the ROM font to your location, modify it, and enable it.


regards,
chris

**Comment by Fabrizio-Caruso** [comment]
THANKS A LOT guys!
I managed to implement some half-decent user-defined characters in the Atari version!

![atari_5](https://user-images.githubusercontent.com/29057615/30670455-aacd3676-9e62-11e7-88fd-e8da98ec3e37.jpg)
