### ISSUE TITLE
NES colors in conio not working

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#508]
I get no colors in conio for the NES target but the NES hardware should support colors in the conio standard resolution.
Is it a bug? Or missing feature?

**Comment by oliverschmidt** [comment]
> Is it a bug? Or missing feature?

Given that cc65 is an open source project it's fortunatley not very hard find at least a hint on this for yourself. Check out https://github.com/cc65/cc65/blob/master/libsrc/nes/color.s and you'll see even without 6502 assembler knowledge in https://github.com/cc65/cc65/blob/master/libsrc/nes/color.s#L16-L17 that textcolor() and bordercolor() don't do anything by design. However https://github.com/cc65/cc65/blob/master/libsrc/nes/color.s#L19-L49 indicate that bgcolor() is supposed to do something.

BTW: I consider it a bug that NES textcolor() and bordercolor() just return 0. They are supposed to return the current color value. See: http://cc65.github.io/doc/funcref.html#textcolor

**Comment by Fabrizio-Caruso** [comment]
Thanks

@oliverschmidt, is the lack of colors due to a constraint of the NES hardware such as for the Atari and AppleII? 
Is a it a missing feature that will be implemented eventually? or a missing feature not worth to be implemented for other reasons?

**Comment by oliverschmidt** [comment]
I don't know the answers to your questions. I neither know the NES hardware nor the plans of potential NES C Library contributors. I could only help you so far as I did in helping you to see what is currently supposed to work (and therefore worth trying to get working) and what plainly doesn't exsist (and therefore not worth investing any time).

**Comment by oliverschmidt** [comment]
BTW: Those are questions worth posting on the cc65 dev mailing list.

**Comment by Fabrizio-Caruso** [comment]
Thanks @oliverschmidt ! I have sent a message to to mailing list!
