### ISSUE TITLE
Historic git tag

### ISSUE THREAD

**Issue by uffejakobsen** [cc65/cc65#536]
Hi,

I need to dig into some historic releases of cc65 - in order to figure when and why an old project of mine stopped working when compiled with cc65.

I know for sure that it worked with the last cc65 release released by uz - 2.13.x something i think....

Could you make a git tag that marks the last cc65 released by uz
Thanks in advance

**Comment by mrdudz** [comment]
Am Sonntag, 26. November 2017, 23:45:35 CET schrieb Uffe Jakobsen:
> Hi,
> 
> I need to dig into some historic releases of cc65 - in order to figure when
> and why an old project of mine stopped working when compiled with cc65.
> 
> I know for sure that it worked with the last cc65 release released by uz -
> 2.13.x something i think....
> 
> Could you make a git tag that marks the last cc65 released by uz
> Thanks in advance

mmmh wouldnt that be "before it moved to github"? *shrug*

-- 

http://www.hitmen-console.org    http://magicdisk.untergrund.net
http://www.pokefinder.org        http://ar.pokefinder.org

No matter what the anticipated result, there will always be someone eager to 
(a) misinterpret it, (b) fake it, or (c) believe it happened according to his 
own pet theory.

**Comment by spiro-trikaliotis** [comment]
As we preserved the SVN history, it is all there.
The last commit by Uz is e6aa00b339e1f36.

It can be accessed by remote/origin/master.

**Comment by oliverschmidt** [comment]
This GitHub repo contains the complete history all the way back to https://github.com/cc65/cc65/commit/579491e8a41d385a60dc9aaf51b1bdb47bae2cc9

**Comment by uffejakobsen** [comment]
I was actually asking if it made sense to make a tag that would make it easier to checkout....
Personally I think that it would be quite useful - calling it something like V2.13.9 - any tag name would work here...

**Comment by oliverschmidt** [comment]
> I was actually asking if it made sense to make a tag [...]

I see. However I'm unsure how to know which of Uz' commits was actually the last before he created a new version.

**Comment by spiro-trikaliotis** [comment]
I thought that I had converted Uz' SVN to GIT with tags and branches. However, they are not in the repository on Github.

I will check my "original" that was used as basis for the Github repository when I find some time. Hopefully, it is with tags, and I just forgot to upload them. It will take some time, though, as this version is in my backup.

**Comment by spiro-trikaliotis** [comment]
Ok, I had a look.

The SVN of Uz does *not* contain any tags, at least not in the standard format expected in SVN! That's why these were not converted over to git.

I had a look into the versions and found the following mapping:
2.13.3 = SVN r5495 = git baa6c53dec6e3192
2.13.2 = SVN r4615 = git 28736e9a17954fb
2.13.1 = SVN r4538 = git 41f77572043112ace
2.13.0 = SVN r4326 = git ca5ada12bae21502cd
2.13.0rc4 = SVN r4304 = git 6c0960819e263b55bee
2.13.0rc3 (does not exist, as it was not correctly tagged, and was withdran
2.13.0rc2 = SVN r4296 = git ba46bab0097d9c02a7f67
2.13.0rc1 = SVN r4259 = git 3c6e8087f17b58233616
2.12.0 = SVN r3862 = git 6ecca264e4541336d40

I cross-checked with the Windows binary of cc65 2.13.3  (which is the only one downloadable from his server, as the dir old/ is empty on his ftp) and got:

...>cc65 --version
cc65 V2.13.3
SVN version: 5495

So, it fits.

Please note that the SVN revisions given above do not have an exact correspondance in the git, as svn counts every tag as new revision. For example, 2.13.3 is SVN r5495, but r5495 does not exist in the git. The git hash baa6c53dec6e3192 is the one of r5494. This makes sense, as r5495 was the commit that created the tag. There were no more changes.

**Comment by oliverschmidt** [comment]
@spiro-trikaliotis: Thanks for your effort :-)

I added git lightweight tags according to your findings. Now we have:

```
$ git tag
V2.12.0
V2.13.0
V2.13.0rc1
V2.13.0rc2
V2.13.0rc4
V2.13.1
V2.13.2
V2.13.3
V2.14
V2.15
V2.16
```

**Comment by uffejakobsen** [comment]
Thank you both (@oliverschmidt and @spiro-trikaliotis) for your detailed efforts.
It is much more than I expected - 👍 
THX :-) 👍

**Comment by oliverschmidt** [comment]
Thanks for the nice feedback :-)
