### ISSUE TITLE
[Atari 8 bit][MODE 1] clrscr resets colors previously set with _setcolor

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#546]
It seems that clrscr is now resetting colors previously set with
_setcolor_low

**Comment by groessler** [comment]
You cannot use clrscr with a mode 1 screen. The mode1 screen is 20x24 chars, while clrscr wants to clear 40x24 chars. It will stomp over the area following the screen memory, which are GTIA hardware registers if BASIC is not enabled.
But I think this should just give a short color "flicker" because the GTIA registers are reinitialized by the VBI handler.
