### ISSUE TITLE
Support for condes tables with 3 byte addresses?

### ISSUE THREAD

**Issue by benvanik** [cc65/cc65#569]
I'm trying to use `.condes` from ca65 (not C) and require 3 byte addresses in the condes tables. Right now it's hardcoded to 2 bytes and will die if a condes is registered in a segment with a 3 byte address:
https://github.com/cc65/cc65/blob/709ee6a28b1375222d44590a57e93d732966f8bf/src/ld65/condes.c#L215-L216
The error that triggers is a `SEG_EXPR_RANGE_ERROR` from the check here:
https://github.com/cc65/cc65/blob/709ee6a28b1375222d44590a57e93d732966f8bf/src/ld65/segments.c#L435-L438

The system I'm developing for (SNES) has code in different banks that requires the 3rd byte to make the subroutine calls. I've verified things work by changing the hardcoded 2 to a 3 but would like to get this change upstreamed for others to benefit from.

What's a good way to allow tables with 3 byte addresses? An additional attribute on the config CONDES bit for `addresssize=3`? Before I made the changes I wanted to see what you thought about an approach like that :)

(this error path is what causes Issue #568)

**Comment by oliverschmidt** [comment]
Let me start with saying that I personally have no experience whatsoever with using ca65 for the 65C816 so what I write may be totally bullsh...

Looking at http://cc65.github.io/doc/ca65.html#ss11.96 it seems to me that it is natural for a segment to have an address size. http://cc65.github.io/doc/ld65.html#ss5.9 says that the CONDES FEATURE refers to a segment: "This attribute tells the linker into which segment the table should be placed. If the segment does not exist, it is created."

I presume that your scenario only works because the segment in question already exists and is a 3 byte segment. I guess you'd otherwise fail because of the hardcoded `ADDR_SIZE_ABS` in https://github.com/cc65/cc65/blob/709ee6a28b1375222d44590a57e93d732966f8bf/src/ld65/condes.c#L199 and (?) https://github.com/cc65/cc65/blob/709ee6a28b1375222d44590a57e93d732966f8bf/src/ld65/condes.c#L202

So to me it would seem rather natural to have ld65 default to 2 byte addresses but if the segment the CONDES table is supposed to be placed in already exists and happens to be a 3 byte segment then a 3 byte CONDES table is created.

I guess that can be done by leaving https://github.com/cc65/cc65/blob/709ee6a28b1375222d44590a57e93d732966f8bf/src/ld65/condes.c#L199 alone but then getting the size of the segment in question and use its address size for (?) https://github.com/cc65/cc65/blob/709ee6a28b1375222d44590a57e93d732966f8bf/src/ld65/condes.c#L202 and https://github.com/cc65/cc65/blob/709ee6a28b1375222d44590a57e93d732966f8bf/src/ld65/condes.c#L216

Apart from that I must admit that I don't understand why your scenario works because http://cc65.github.io/doc/ca65.html#ss11.14 explicitly says: "All symbols are exported as an absolute (16 bit) symbol." So where does ld65 get the third byte from?

**Comment by oliverschmidt** [comment]
I'll close this due to inactivity.
