### ISSUE TITLE
[PCE][info] Does anyone know how to activate memory banks other than $E000-$FFFF?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#586]
Hi 

I am still struggling with the PCE. 
I could not find any information on how to use more than 8k in the $E000-$FFFF.
I think I know how to tell the linker to use more.
I think I know how to tell the linker what code goes where.
But the produced 16k rom (or bigger) won't start if I use anything different than a single 8k section.

I wonder whether I have to initialize the machine somehow to activate some other memory banks?
Should I use the bank attribute? How?
Does anyone here know where I can get more information?

Thanks in advance for any hint!

  Fabrizio

**Comment by oliverschmidt** [comment]
> I think I know how to tell the linker what code goes where.

Great.

However, I hope you are aware that beside that you need to make your code actually do the banking. There's no automatism whatsoever in cc65 saying "oh, I'm currently in bank A, the function I'm supposed to call now is in bank B so I need to switch to bank B (and back to A on return).

Furthermore, if there's no memory area that's is not banked you'll likely have to duplicate some small parts of code to be present in both banks at the very same spot and have that code do the actual banking like a "trampoline". Or you have that "trampoline" copied to RAM and executed there.

And finally you need to think about your readonly-data to be available in the "right" bank when you need it. This again is something you need to take care of yourself.

https://github.com/cc65/cc65/blob/master/samples/overlaydemo.c might be (at least somewhat) interesting to you. It's about overlays but from the perspective of the running code it doesn't matter if the content of some address range changes because of banking or because of loading different content to it. The program is however limited to the "easy" scenario with lots of memory not banked thus allowing to keep all readonly-data and the content changing code in not-changing memory.

http://cc65.github.io/doc/cc65.html#ss7.18 might be interesting to you too. Presuming that the "content changing" is actually banking and can be done in a few lines of assembly code one can move from expressing the action of banking in an imperative style to expressing it in an (efficient) declarative style. The `wrapped-call` pragma is usually used together with the `code-name` pragma.

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt, yes and no because I don't understand PCE memory addressing.
I assume that a 6502-derivative can address at the same time more than 8k.
PCE memory is segmented in 8k blocks but the CPU should be able to see at least 64k of total ram/rom/input/output at the same time without any bank switching.

I would like to see two 8k rom bank at the same time all the time without any switching on the fly.
I cannot find any documentation or tutorial. 
So I thought that maybe something has to be done only at startup once and for all if no more than 64 of total memory are used.

**Comment by oliverschmidt** [comment]
> Does anyone here know where I can get more information?

I was curious to see how my experience would be if I had to find that information. It wasn't exactly trivial but not __*that*__ hard either...

Looking at http://www.magicengine.com/mkit/index.html sections 'Memory Mapping' and 'Bank Map' (incl. the note "After a RESET bank $00 is automaticaly mapped into page 7.") it seems that the default setup is made of these instructions:
```
LDA $FF
TAM 0
LDA $F8
TAM 1
```

Now looking at the cc65 startup code I see:

https://github.com/cc65/cc65/blob/69fbcb30fd393277c93eade43737a52d20582c47/libsrc/pce/crt0.s#L56-L60

Bingo! Looking a few lines further I see:

https://github.com/cc65/cc65/blob/69fbcb30fd393277c93eade43737a52d20582c47/libsrc/pce/crt0.s#L62-L74

So it's no surprise that there are only 8kB ROM possible. The default setup only maps 8kB and the cc65 startup code stays with the default setup. The question coming up might be: Why?

Anyhow, it seems to me that this information is a great starting point for exploration. I personally wouldn't modify the startup code but rather create a linker config that makes sure that the startup stays in bank $00 and use a few lines of inline assembler in main() to map more ROM.

Later on one might discuss why both the cc65 startup code and the default linker config don't just support more ROM in the first place.

**Comment by Fabrizio-Caruso** [comment]
Thanks a lot @oliverschmidt !
I am learning... My starting point is very low.  So far the only  Assembly code I have ever written is two bytes: "EOR $FF", which is contained in my PR to fix Gamate joystick behavior.
Hopefully I will improve over time.
It would be very useful to have a somehow selectable alternative startup code and linker config to access more than 8k rom without having to write Assembly code for this common use-case.
No every CC65 user codes in Assembly. Some people would like to use primarily or only C.

**Comment by groessler** [comment]
> I am learning... My starting point is very low. So far the only Assembly code I have ever written is two bytes: "EOR $FF", which is contained in my PR to fix Gamate joystick behavior.

Assembly language is no black magic. See http://6502.org/tutorials/  to get started.

> It would be very useful to have a somehow selectable alternative startup code and linker config to access more than 8k rom without having to write Assembly code for this common use-case.

If I would have to solve this problem, I would copy the pce crt0.s over and uncomment some of the lines which enable other banks. Then adjust the cfg file accordingly and compile this crt0.s together with my program (effectively replacing the crt0.o file of the pce runtime library). Then see what happens....

**Comment by Fabrizio-Caruso** [comment]
@groessler, my code should not depend on a modded version of one of many compilers I am using. Can I do what you propose without touching the compiler?

My code should remain separated from the compiler code. I would rather suffer to find a way to do it in Assembly inside my code. I hope we will get some option to make the PCE more usable in plain C for bigger than 8k roms.

**Comment by groessler** [comment]
@Fabrizio-Caruso, I wasn't talking about "modding" the compiler.

If you copy the existing crt0.s to your code, modify it, and use it, you are in no way "modding" the compiler. Your program can still be compiled by the stock compiler. The only thing you would need to monitor is that whther cc65's crt0.s gets changed. Then you probably want to introduce these changes to your private version.

@oliverschmidt's response used another approach, he suggested to map in the new banks somewhere in main(). That's just different idea about how to investigate/solve the problem.

Anyway, you will have to use some assembly language in your program, unless...

CC65 supports more than 8K ROMs "out of the box".

Currently this is not supported, obviously. So CC65 needs to be changed. For this to happen, someone has to do the work.
Unless you can convince a maintainer of a port to do this, you'll have to do this yourself.

So what you can do is to use my approach and modify crt0.s in a way that your program works. And modify the linker config, too, accordingly. And everything else what might be needed.
When it works for you program you can submit a Pull-Request with the modified files. After it gets accepted (which might not happen immediately, but will happen if you are dedicated), your program will work with the new release of the compiler, "out-of-the-box", without assembly changes in your program.

**Comment by polluks** [comment]
Didn't make @mrdudz this target? So ask him.

**Comment by mrdudz** [comment]
i did! but that was long ago, and it was also my first (and last) PCE code - so cant really tell you anything about it either. there probably was a reason for not enabling all the ROM - but i dont remember.

**Comment by groessler** [comment]
Ok, offer: If someone donates me a PCE, I would adopt maintainership of the PCE target :-)

**Comment by Fabrizio-Caruso** [comment]
@groessler, I will try to see how to enable roms and if I succeed I will let you guys now and try a pull request unless @mrdudz or some else implements some mechanism to make the PCE target more usable for people who only use C and want to create a rom bigger than 8k.
I will definitely try and share whatever useful knowledge I get.

**Comment by greg-king5** [comment]
> There probably was a reason for not enabling all the ROM -- but, I don't remember.

Any attempt to make a _standard_ configuration for bigger ROMs will fail.  ROM space would be wasted.

As far as programs are concerned, there is no such thing as a 16K ROM; there are two -- separate -- 8K ROMs.  The two ROMs are mapped backwards:  the low ROM is mapped above the high ROM.  A ROM can't "flow" into the other one.

A programmer must choose where to put each program's segments, so that he uses as much of those ROMs as possible.  (Only STARTUP and VECTORS have a required bank.)

**Comment by greg-king5** [comment]
I should be able to make the standard "crt0" map 8K, 16K, and 32K carts.  Only ROM bank 0 will be isolated.  The other banks will "flow" into the next higher bank.

**Comment by oliverschmidt** [comment]
> As far as programs are concerned, there is no such thing as a 16K ROM; there are two -- separate -- 8K ROMs. The two ROMs are mapped backwards: the low ROM is mapped above the high ROM. A ROM can't "flow" into the other one.

Just to make sure that there are no misunderstandings: Do you see this as a limitation or the PCE or as a limitation of ld65?

Because it seems to me that if the STARTUP segment would be placed right below the 6502 vectors and if the startup code would map the upper 8kB to $C000-$DFFF then one could easily have a single contiguous ROM memory area from $C000 to the STARTUP segment. I think one could even hack it with the current ld65:
1. Manually move STARTUP up as far as possible just before it overflows.
2. Post-process the 16kB ld65 output with some tool that swaps the first and second 8kB.

**Comment by greg-king5** [comment]
When I say "can't flow", I mean that program code can't execute up to the end of the bank; and then, continue executing in the beginning of the next bank (the hardware vectors block it).

**Comment by oliverschmidt** [comment]
> When I say "can't flow", I mean that program code can't execute up to the end of the bank; and then, continue executing in the beginning of the next bank (the hardware vectors block it).

I think I understood well that what you want to express with "can't flow". The aspect I consider interesting is if - as a wrote above - it is from you POV a PCE issue or a ld65 issue.

**Comment by greg-king5** [comment]
I was wrong!  We can have a standard configuration file that builds 8K, 16K, and 32K cartridge images.  The solution is the post-processing that Oliver proposed.

**Comment by oliverschmidt** [comment]
@greg-king5: Thanks for the clarification !

**Comment by Fabrizio-Caruso** [comment]
THANKS A LOT guys!

**Comment by Fabrizio-Caruso** [comment]
There may be a serious problem (maybe stack-related):
#596
