### ISSUE TITLE
Version 2.17 Error on compile

### ISSUE THREAD

**Issue by jespicas** [cc65/cc65#638]
Hi,

If clone last version of project and try do compile examples found in other projects https://github.com/algofoogle/nes-gamedev-examples  give this error:
ld65: Error: 1 unresolved external(s) found - cannot create output file

I download versio 2.15 and same code works, without any error.

**Comment by oliverschmidt** [comment]
- In order to say anything at all it's necessary that you provide the information *which* symbols aren't found.

- You may want to consider creating an issue for the GitHub repo you mentioned above asking to adjust the examples to the latest cc65.

- cc65 changes over time and projects relying on some rather internal aspect of cc65 easily become incompatible and need adjustment.

**Comment by groessler** [comment]
@jespicas: can you give more details? The project you referred to doesn't have any Makefiles, so it's difficult to find out how to compile the source codes.

Best would be to post your complete cc65 command line and the errors you get.

**Comment by jespicas** [comment]
Now I tried to reproduce the error. I downloaded again last version of master repository and I compiled a project doesn't works, but seems not it's ok therefore the bug not exist.
