### ISSUE TITLE
How to do an interrupt that fills a ring buffer?

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#672]
I've been thumbing through trying to find examples on how best to do this in CC65, but, how can I write an interrupt routine that fills a ring buffer?

**Comment by mrdudz** [comment]
you'd write it in assembly. how exactly depends on your target.

**Comment by groessler** [comment]
And, yoiu need a read index and a write index. If they are the same, the buffer is empty. Just write to it using the write index, if not one less than the read index (then the buffer is full), increase the write index (wrapping to zero at the end of the buffer area). Read operation more or less the reverse: Unless read index == write index, read from read index and increase it (...wrap to zero when needed...).

**Comment by tschak909** [comment]
I do know how ring buffers work, just thought I'd ask to see if I could write an interruptor in C.. guess not. sigh.

-Thom

**Comment by groessler** [comment]
probably better done in assembly. Also simpler :-)

**Comment by mrdudz** [comment]
interrupt routines have a LOT of overhead when you write them in C, which makes them kindof of useless in practice. its possible, but not worth the trouble :)

**Comment by tschak909** [comment]
ok, so will punt for later.

**Comment by oliverschmidt** [comment]
Maybe it's worth mentioning that the serial I/O driver "template", e.g. present in https://github.com/cc65/cc65/blob/master/libsrc/c64/ser/c64-swlink.s fills a 256 byte receive ring buffer  from an interrupt. In fact it's worth mentioning it for two reasons:
* You can "just" remove all serial stuff from that code to have a great starting point for whatever you want to do.
* Just in case you asked that question because you want to create a ring buffer for bytes received via serial I/O in order to make sure they don't get lost you see that such a ring buffer is already in place.
