### ISSUE TITLE
Can't get apple2 hires TGI driver working

### ISSUE THREAD

**Issue by sehugg** [cc65/cc65#686]
I compile one of the examples:

    bin/cl65 -o a.out -t apple2 -C apple2-hgr.cfg testcode/lib/apple2/hgrtest.c testcode/lib/apple2/werner.s

And then disassemble:

    da65 -S 0x7c9 a.out

I get this at $803:

        ldx     #$FF
        txs
        jsr     L4F1E

But $4F1E is the symbol `_tgi_vectorfont`, and the program crashes. Am I doing something wrong?

**Comment by oliverschmidt** [comment]
I just used the very command line you posted above and things worked like a charm for me. Adding `-m a.map` might help you to analyze your issue. You may want to look at my (renamed) 
[map file](https://github.com/cc65/cc65/files/2120768/a.map.txt) for your reference.

In general I'd like to mention that the sample we're talking about here is a very specific thing (a program "loading over the hires screen" containing a hires image). If you just want a program using the hires screen then you'd rather use the default linker config file and just set the start address to $4000 as done at https://github.com/cc65/cc65/blob/master/samples/Makefile#L111

However, if you're really into loading over the hires screen then you may want to consult your map file and (nearly) fill the gap between $80x and $2000 with some code (instead of lots of zeros) by placing some code in the LOWCODE segment.

**Comment by polluks** [comment]
@sehugg _tgi_vectorfont? This should be "jsr init".

**Comment by sehugg** [comment]
Thanks. Turns out my problem was an unrelated emulator issue; my debugging was confused by the TGI vars overwriting the TGI installation code. Now I know!

**Comment by oliverschmidt** [comment]
Thanks for the feedback.
