### ISSUE TITLE
PLATOTerm64 apple2 make dist disk?

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#698]
Hi, I'm getting the Apple2 port of PLATOTerm64 ready to build.
Have done the necessary initial work to fan out the apple2 target in my tree, and I have applecommander 1.4 working, and it is taking my prodos disk with prodos.system ready to go. I also have the apple2-system.cfg in my apple2 build dir, and it's building. 

I have two questions:
(1) how best to coax applecommander to copy the .ser and .mou drivers with the correct type?
(2) how to pass additional switches to reserve the 1 page of hires graphics?

-Thom

**Comment by tschak909** [comment]
Figured out the first one, but I'm actually curious if it's possible to create a system file AND reserve the page at $2000 for hires graphics?

**Comment by tschak909** [comment]
If I use apple2-hgr, I get:
ld65: Warning: src/apple2/apple2-hgr.cfg(17): Segment `DATA' overflows memory area `MAIN' by 2006 bytes

ugh.

-Thom

**Comment by oliverschmidt** [comment]
> how best to coax applecommander to copy the .ser and .mou drivers with the correct type?
> Figured out the first one

Nevertheless: See https://github.com/cc65/cc65/blob/master/samples/Makefile#L261. Important is to is `-p`. Using `rel` is more my personal taste.

> (2) how to pass additional switches to reserve the 1 page of hires graphics?

I presume you refer to http://cc65.github.io/doc/apple2.html#ss7.1 saying "Note that programs using this driver will have to be linked with -S $4000 to reserve the first hires page".

Looking at http://cc65.github.io/doc/ld65.html#ss2.1 you see that `-S` sets the start addr. Then looking at  http://cc65.github.io/doc/cl65.html#s2 you see that doing the same with cl65 requires `--start-addr`.

**Comment by oliverschmidt** [comment]
> I also have the apple2-system.cfg in my apple2 build dir, and it's building.

- Again: Don't copy around cc65 files. Neither .h nor .lib nor .cfg files are meant to be copied anywhere nor checked in into repositories using cc65! The cc65 tools find those files where they are! and with the right technique your Makefile can find the .ser and .mou files too without copying them around.

- Guess why apple2-system.cfg isn't the default Apple II config file. Because it's only useful for a special purpose. Just stay with the default config file.

**Comment by oliverschmidt** [comment]
> but I'm actually curious if it's possible to create a system file AND reserve the page at $2000 for hires graphics?

No. However, you don't want to create a system file in the first place.

> Segment DATA' overflows memory areaMAIN' by 2006 bytes

Again, the cc65 doc is your friend: http://cc65.github.io/doc/apple2.html#s5

It says

> The easiest (and for really large programs in fact the only) way to have a cc65 program use the memory from $800 to $2000 is to link it as binary (as opposed to system) program using the default linker configuration apple2.cfg with HIMEM set to $BF00 and load it with the LOADER.SYSTEM utility. The program then works like a system program (i.e. quits to the ProDOS dispatcher).

 Doesn't it feel somehow as this is exactly the very situation you are in? ;-))

**Comment by oliverschmidt** [comment]
> If I use apple2-hgr [...]

apple2-hgr.cfg is for a special purpose. http://cc65.github.io/doc/apple2.html#ss4.3 says "for a program including a hires page". Do you do so? I don't think so. So why are you using apple2-hgr.cfg?

I guess you got the point I want to make. Please read the cc65 documentation. You can save yourself quite some time by doing so - and some time of mine ;-)

**Comment by oliverschmidt** [comment]
To summarize the info in the docs for building an Apple II TGI program of significant size:

- Use the default linker config. Set the start address to $4000.

- Set `__HIMEM__` to $BF00 and load the program via LOADER.SYSTEM. For the latter rename LOADER.SYSTEM to <your_program_name>.SYSTEM. This is also the way to allow your program to be automatically started on boot.

- If you do any file I/O, either by yourself or by loading drivers like .TGI, .SER, .MOU then your program uses the heap as the Apple II file I/O uses the heap. So even if you don't use the heap yourself (aka call malloc()) do a `_heapadd ((void *) 0x0800, 0x1800);` before your first file I/O (or loading a driver). This way you don't touch the primary heap above your program for those operations.

**Comment by oliverschmidt** [comment]
If you still run into memory problems then have $C00 or $1000 bytes of your code moved into the Apple II language card, see: http://cc65.github.io/doc/apple2.html#s3 - it sounds complicated but is easy after all.

**Comment by oliverschmidt** [comment]
If after using the language card you still run into memory problems then quit loading drivers dynamically on the Apple II. There's only one relevant .TGI driver, only one .SER driver and only one .MOU driver. Just link them all statically.

This way you don't link the driver loader. But you make less use of the memory region $800-$2000. I say less use because you use $400 bytes of the heap of every open file. If you have never more than one file open at a time this means that you can savely malloc() at least $1300 bytes without touching the primary heap.

So the idea is to replace some large uninitialized global variables with pointers to malloc'ed memory. However, don't do so with performance critical stuff as the pointer indirection makes things (somewhat) slower.

**Comment by oliverschmidt** [comment]
If you don't want to make use of malloc() or you can't make use of malloc() because ...

- the performance hit of accessing your uninitialized global variables
- you don't have that much uninitialized global variables in the first place, but rather just "too" much code (or initialized variables).

... then use apple2-hgr.cfg and have code (or initialized variables) placed in the memory region $800-$2000. See https://github.com/cc65/cc65/blob/master/testcode/lib/apple2/hgrtest.c#L6 how to do it. Note that this can be combined and in fact should be combined with having code moved into the language card. 

__NOTE__: It's up to you to decide which code goes where! Therefore you need to create and consult a map file to understand you code sizes and decide. You'll always have some bytes unused in the different code areas.

**Comment by oliverschmidt** [comment]
If you use apple2-hgr.cfg then any file I/O you do makes use of the heap. If you don't make use of the heap yourself then you can gain even more memory by avoiding to load the heap manager "just for the file I/O".

Presuming you have never more than one file open at any time set the start address of your program to $C00 (while still using apple2-hgr.cfg). Then follow http://cc65.github.io/doc/apple2.html#ss5.3 which results in exactly one $400 byte file I/O buffer at $800.

__NOTE__: You need to consult your map file to check that everything works as expected and that the heap manager is actually gone.

**Comment by oliverschmidt** [comment]
If you use apple2-hgr.cfg then your program file contains (at least) $2000 zeros. If you are interested your can replace $2000 bytes of those zeros with a hires graphics picture that is be displayed after initializing the hires screen but before clearing it. See https://github.com/cc65/cc65/blob/master/testcode/lib/apple2/hgrtest.c#L1 and https://github.com/cc65/cc65/blob/master/testcode/lib/apple2/werner.s on how to do that.

**Comment by tschak909** [comment]
Have been able to bring up PlatoTERM on the AppleII.

https://i.imgur.com/ijkOTCm.png

Silly question: What _IS_ an enhanced Apple //e (a la apple2enh) ? Does this reasonably map to a significant amount of hardware as to be viable to use for anything but very targeted specific uses?

-Thom

**Comment by oliverschmidt** [comment]
>Have been able to bring up PlatoTERM on the AppleII.

Cool :-)

>What IS an enhanced Apple //e (a la apple2enh) ? Does this reasonably map to a significant amount of hardware as to be viable to use for anything but very targeted specific uses?

Yes.

- It's the "minimal" Apple II with a 65C02 CPU (in contrast to a 6502 CPU). cc65 has specific 65C02 support which is activated for that target: https://github.com/cc65/cc65/blob/master/src/common/target.c#L200-L201

- It's the "minimal" Apple II with support for inverse lowercase char display in text mode. Therefore cc65 apple2 programs (in contrast to cc65 apple2enh progrms) don't display any lowercase chars at all.

Apart from that, cc65 doesn't have an apple2e target (a la non-enhanced Apple //e). Therefore you need to use the apple2enh target to get any support specific to the Apple //e "in general". Beside some minor things this is the support for the 80 column text mode. Note that it is technically possible to have an (enhanced) Apple //e without 80 column hardware but in fact they are "all" equipped with it.

**Comment by polluks** [comment]
@tschak909 "...for your Commodore 64" ;-)

**Comment by oliverschmidt** [comment]
Isn't every retro machine a C64 after all ? ;-))

**Comment by oliverschmidt** [comment]
It seems save to consider the question(s) answered.
