### ISSUE TITLE
Going through pointer slow down code too much, am stumped.

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#708]
I've added in support for font downloading into PLATOTerm, but it looks like the addition of the additional pointer indirection was enough to slow it down too much, and the serial buffer overruns...

https://github.com/tschak909/platoterm64/compare/charset_loading#diff-6b93c499fcdcb49a46b73101a04bb76c

Am trying to figure out what I can do...

-Thom

**Comment by oliverschmidt** [comment]
> [...] slow it down too much, and the serial buffer overruns...

Sorry but I think we already discussed that in great detail. So I'm just rephrasing:

With a dumb terminal you can say the slowest thing is scrolling the screen up by one line. If you can do that in the time a char is received you're fine. But with a complex terminal you just need flow control. And with flow control "overruns because of slow" are just not possible. And - as discussed - if the infrastructure you have at hand (C64 hardware, cc65 serial driver, TCPSER, Wifi Modem, ...) doesn't give you flow control then you should implement your own flow control layer above. Your server program runs on an emulated hardware. As far as I understand that emulation maps the original I/O ports to TCP connections. I presume that the emulation supports flow control on those emulated I/O ports via TCP flow control. In that case you should implement a proxy server.

The cc65 serial driver has a 256 byte ring buffer so I should always be possible to receive lets say 250 bytes without a risk of a overrun. So let's just presume a 250 byte packet size for this example

The proxy server does on the socket to the real server a `read(sock, buffer, 250);` The return value is something between 1 and 250. The proxy puts that value as two bytes on the socket to the client. Then it puts the 1-250 bytes on the socket to the client. Then it does a read() on the socket to the client. How the protocol from the client to the proxy server looks like depends e.g. on the question if you need 8-bit transparency - as discussed. Anyhow, before receiving something from the client the proxy does no further read on the socket to the real server. This way the TCP window closes and the real server sees back pressure on its socket.

The client reads the two byte packet length and then reads as many bytes as indicated. After that it sends some acknowledgement to the proxy server.

With such an layer in place there can't be any overruns anymore no matter what the client does. It could even download a file and write it to the C64 drive with the stock DOS and there would be no overrun. I don't see any point in investing further effort in this project before there's no reliable flow control in place.

> [...] it looks like the addition of the additional pointer indirection was enough to slow it down [...]

Totally independent from making sure that slowness doesn't cause functional issues but is limited to a less-than-optimal user experience by employing flow control I suggest to implement the char drawing using assembly. Char output is clearly the main task of a terminal program. And using a TGI setpixel() for every char glyph pixel just won't get you there. I think one of the great benefits of cc65 is how well C and asm code can be integrated. So you can implement your whole protocol logic (plus all local UI) in C and use TGI for drawing lines etc. But for char output you should spot-optimize and have your own custom asm code. And even with asm I'd suggest to have two variants as you have today in C - one for default attributes and one flexible one. Or you start by only replacing the default attributes C code with asm and see where this gets you on PLATO "pages" you consider relevant/typical.

If you do that successfully on the C64 then I commit to assist you in porting that asm code from the C64 to the Apple II targeting its 280x192 monochrome screen.

**Comment by tschak909** [comment]
I know this needs to be done... Unfortunately, the assembly is not my strong suit. While I can spend time getting to know the peculiarities of the C64's bitmap mode (I do know that it is arranged with bytes corresponding to lines in an 8x8 block, rather than say, linear in the Atari 800, or the very awkward 64:1 linear interleaving in Apple Hi-Res, my 6502-fu just isn't as well developed. I really need help trying to speed this back up, as my expertise is in the protocol logic. :(

**Comment by tschak909** [comment]
(and yes, this IS with hardware flow control implemented on the C64's userport driver...the swiftlink driver seems to already implement hardware flow control at the driver level and doesn't seem to have these problems...nor does the Apple II's SSC driver...the Atari driver seems to crash upon opening, I will deal with it later.)

**Comment by tschak909** [comment]
I'm actually to the point of thinking that it needs to be done in the NMI handler for up2400, but I need input from someone who knows if I have enough cycles left to do  a simple compare...my (admittedly very novice) assessment of the routine versus the hardware manual means I am basically plodding through this, making every mistake possible...

**Comment by tschak909** [comment]
for the record, am talking about this guy here:
https://github.com/nanoflite/c64-up2400-cc65

the swlink driver has a much easier time of this. it's nice having an actual chip doing the shifting..

-Thom
