### ISSUE TITLE
Need a "seriously none" cfg

### ISSUE THREAD

**Issue by fadden** [cc65/cc65#789]
[SourceGen](https://github.com/fadden/6502bench) attempts to disassemble a binary and generate source code that compiles back into that same binary.  The command line currently uses `--target none`, since SourceGen doesn't want any frills.

The trouble is that the "none" configuration is limited to $6800 bytes, because it declares that the world starts at $1000 and ends at $8000, with $800 bytes of stack.  What I'd like is a way to say, "there's nothing here but code", and be able to drop a 64KiB chunk in that fills an entire bank.

I tried simply dropping the `--target` from the command line and got complaints about a few segments, with an error for BSS.  I tried defining the segments in the generated source file and ended up with 14 bytes of unexpected data at the start of the binary (`0108 0b08 1003 9e32 3036 3100 0000`).  So I'm clearly missing something.

My goal is to be able to generate a single file that can be fed into cl65, with a command line that won't give end users hives.  I'm hoping to avoid having to generate a file pair (source + linker script), so a generally-available "just be a generic assembler" config would be useful.  Alternatively, if the necessary configuration can be done inside the source file, I can generate the appropriate lines.

(I also checked for a way to simply ignore memory area overflows... no such luck.)

**Comment by groessler** [comment]
No `--target` defaults to c64, IIRC.

What's the problem in having a linker script? Linker scripts aren't evil.

**Comment by oliverschmidt** [comment]
> My goal is to be able to generate a single file that can be fed into cl65, with a command line that won't give end users hives. I'm hoping to avoid having to generate a file pair (source + linker script), so a generally-available "just be a generic assembler" config would be useful. Alternatively, if the necessary configuration can be done inside the source file, I can generate the appropriate lines.

Hm...

So you are generating source code from binary code. Why do you do that? Likely because you want to enable the users to do something with the code beside generating the original binary code again ;-)

So you want to support cl65. Why do you want to do that? Likely because you want cl65 users to be able to do something with the code.

As far as I understand people use cl65 because they actually like the idea of separating the assembler from the linker. They like the idea of a project not consisting of one large asm file cluttered with .ORG directive. Or requiring workarounds like a main asm file including sub asm files. As far as I understand they like the idea of not having a "memory plan" like "from $1500-$2000 I have this and from $2000-2300 if have that and ..." but instead having a linker config file describing the structure of the binary and have the asm files generate content that "flows" into that structure.

So maybe your desired single asm file only fulfills your personal idea of an ideal cl65 input but not the idea of a typical cl65 user.

Having that said...

> What I'd like is a way to say, "there's nothing here but code", and be able to drop a 64KiB chunk in that fills an entire bank.

I'm pretty sure that this isn't the (whole) truth. I guess/hope the source code you generate doesn't use only absolute values for JMP/JSR operands but rather supports the concept of labels. But then you must be able to tell the assembler (or rather the linker) what base address to presume when generating the binary code.

From the perspective of a cl65 user this for sure isn't done via some .ORG directive. Instead there are two options:
* Use one of the linker configs coming with cl65. Several of them allow to override the default binary start address with the cl65 option `--start-addr`. The linker config used for `--target none` is one of them.
* Use a project-specific linker config.

> My goal is to be able to generate a single file that can be fed into cl65, with a command line that won't give end users hives.

As you can see from what I wrote above what you ask for is more or less impossible. Either there needs to be a linker config or there needs to be a start address command line parameter the user needs to know the value for. To me personally a linker config seems to fit your scenario better as you can then document a generic command to reproduce the binary using cl65:

`cl65 -t none -C <project>.cfg <project>.s`

BTW: I personally pretty much dislike the need for the `-t none` but I consider changing that to cause too much backward compatibility issues.

**Comment by fadden** [comment]
> I guess/hope the source code you generate doesn't use only absolute values for JMP/JSR operands but rather supports the concept of labels.

If you have 10 minutes to kill, there's a [demo video](https://youtu.be/dalISyBPQq8).  (If not, you can just skip to the [exciting part](https://youtu.be/dalISyBPQq8?t=310).)

> As far as I understand people use cl65 because they actually like the idea of separating the assembler from the linker.

I did get that sense.  I chose cc65 as one of the first assemblers to generate for because (1) it's well supported, (2) other Apple II people have found it useful, and (3) it's very different from Merlin 32, which made it useful for figuring out how much flex to build into various interfaces.

Being able to reconstruct the original binary is an essential first step, because it guarantees the correctness of the disassembly.  As you note, it may not be the last step.

The cc65 assembler is able to handle some [relatively twisted tests](https://github.com/fadden/6502bench/blob/master/SourceGen/SGTestData/Source/2008-address-changes.S) with .ORGs galore.  Generating code this way is easier than defining segments and emitting a separate linker script, but maybe the purpose of SourceGen's cc65 generator should be to create ready-to-relocate output, rather than to express the output minimally.  I've got 64tass and Merlin 32 for anybody who wants it the other way.

It'd be much easier for me if what already works for files < $6800 bytes would work for larger files, but if your intentions for the way the assembler is to be used are heading in a different direction, then it doesn't make sense for you to support this behavior.

**Comment by oliverschmidt** [comment]
> Generating code this way is easier than defining segments and emitting a separate linker script, but maybe the purpose of SourceGen's cc65 generator should be to create ready-to-relocate output, rather than to express the output minimally. I've got 64tass and Merlin 32 for anybody who wants it the other way.

I think that pretty nicely phrases the point I wanted to make in general.

> It'd be much easier for me if what already works for files < $6800 bytes would work for larger files, but if your intentions for the way the assembler is to be used are heading in a different direction, then it doesn't make sense for you to support this behavior.

Here we (seem to) have a misunderstanding. My question what you think users prefer (handling and using a linker config your tool creates vs. having to remember the correct start address to give to cl65/ld65) was *NO* rhetorical question!

So I didn't want to preclude in any way that I might add something that makes things easier for you. I was just questioning if that is what your users expect as output for cl65.

https://github.com/cc65/cc65/blob/master/cfg/none.cfg is supposed to be used by C programs. I could imagine to provide some none-asm.cfg (on the analogy of https://github.com/cc65/cc65/blob/master/cfg/c64-asm.cfg or https://github.com/cc65/cc65/blob/master/cfg/apple2-asm.cfg) supposed to be used by asm programs. But I don't have experience with using .ORG at all so I can't assess if that would help you.

**Comment by silverdr** [comment]
>but maybe the purpose of SourceGen's cc65 generator should be to create ready-to-relocate output, rather than to express the output minimally

@fadden - Yes, precisely. Please follow the path you described so well above - cc65 (ca65) is rather unique in its ability to handle complex setups gracefully (once you master linker configs, that is :-) that other tools are inefficient at. True, it has a learning curve to use it efficiently but going that way pays. And having a tool that could handle things (semi)automatically looks like a very interesting option.

P. S. And while you're at it - maybe at this relatively early stage you could still consider moving development of your highly promising tool to something truly cross-platform? I for one would really be happy to see an intelligent, interactive, and supporting ca65 disassembly tool for 6502 without paying thousands for IDA only to get 6502 there and still no ca65 directly. Even - please excuse the bad word - Java would suit cross-platform better IMHO. Please consider.

**Comment by groessler** [comment]
@oliverschmidt: regarding a "none-asm.cfg". I don't think it's needed. We could make all segments in the current none.cfg "optional".

@fadden: The current none.cfg lets you override all of `__STACKSIZE__`, `__STACKSTART__` and `__ZPSTART__` from the command line (they are "weak"). So you don't have to create a cfg file. But you will need command line arguments to override the values. I would prefer that you generate a customized config file, that's easier for the user I suppose.

**Comment by fadden** [comment]
@silverdr: I believe it can work under Mono with some effort.  I think the WinForms support is far enough along, and my interactions with the API are simple enough, that I can work around the bugs and at least get it running on Linux.  Java is dead to me.

@oliverschmidt: I'm trying to do things the "right way" for a given target.  I assume anybody who chooses to use ca65 has either made their peace with linker configuration files, or figured out some way of avoiding them that gets the job done.  If I had a "just generate bytes, updating the .ORG as we go" flag then I could generate code the way I do for Merlin or 64tass, but if that's the wrong answer for ca65 then let's not do that.

**Comment by silverdr** [comment]
@fadden - Java was only an example (with disclaimer). There are several other options, which don't require much belief. Keeping it working under Mono might be an option too. Just not sure if that doesn't require more efforts than going truly cross-platform. Good luck and keep up anyways!

**Comment by oliverschmidt** [comment]
> I don't think it's needed. We could make all segments in the current none.cfg "optional".

I don't think that this is the problem. you can already successfully do `cl65 -t none test.s` with test.s just containing `rts` and you get a 1 byte file containing 0x60.

> But you will need command line arguments to override the values. I would prefer that you generate a customized config file, that's easier for the user I suppose.

That are exactly the two options I'm talking about all the way ;-)

> If I had a "just generate bytes, updating the .ORG as we go" flag then I could generate code the way I do for Merlin or 64tass, but if that's the wrong answer for ca65 then let's not do that.

It seems to me that this is a true statement. Maybe it motivates you to think from the opposite side. If you do it "right" for ca65/ld65 then people can just look at the generated linker config and get a first rough understanding of the structure of the binary file processed without scanning the source for all those .ORGs.
