### ISSUE TITLE
Cannot build documentation

### ISSUE THREAD

**Issue by MJoergen** [cc65/cc65#813]
After running the following four commands:
```
git clone git@github.com:cc65/cc65.git
git checkout tags/V2.17
make
PREFIX=/opt/cc65 make doc
```
I get the following errors:
```
Processing file ../doc/c64.sgml
nsgmls:<OSFD>0:254:3:E: entity end not allowed in end tag
nsgmls:<OSFD>0:254:3:E: end tag for element "V" which is not open
nsgmls:<OSFD>0:254:3:E: end tag for "VERB" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:252:9: start tag was here
nsgmls:<OSFD>0:254:3:E: end tag for "TSCREEN" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:252:0: start tag was here
nsgmls:<OSFD>0:254:3:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:3:0: start tag was here
LinuxdocTools::process_file: nsgmls failed with exit status 1. Aborting ...
make[1]: *** [Makefile:37: ../html/c64.html] Error 25
make: *** [Makefile:18: doc] Error 2

```
I'm on a Fedora 29 system.
I'm using the following versions:
```
linuxdoc-tools-0.9.72-6.fc29.x86_64
opensp-1.5.2-30.fc29.x86_64

```

I can't make any sense of the error message.

**Comment by oliverschmidt** [comment]
Unfortunately the only thing I can contribute here is to state that it works here: https://travis-ci.org/cc65/cc65/builds

**Comment by spiro-trikaliotis** [comment]
I know this problem very well. With OpenCBM, the documentation always was able to build on one distribution, but not on another. It was always subtle differences between the versions of the linuxdoc toolchain that broke it. One has to be very careful in order to modify the files so neither variant is broken.

linuxdoc works in a multi-step process. It preprocesses the file and then gives it to other tools.
In this case, nsgmls complains about the preprocessed file.

When I had to debug this, I looked into the /tmp directory for the intermediate file, saved it, an looked the line numbers there. IIRC, the line

nsgmls:<OSFD>0:254:3:E: entity end not allowed in end tag

means that nsgmls complains about line 254, column 3. There, you will find some text that will help you find the place in the original c64.sgml file.

It's a very low-level way to debug it, but I did not find any other way back then.

**Comment by MJoergen** [comment]
I've now tried on two machines (one laptop and one desktop), both running Fedora 29 with all latest updates. The documentation compiles fine on the desktop, but fails (with the above error message) on the laptop. The version of linuxdoc-tools and opensp (and of course cc65) are the same on both machines.

What other packages are involved in generating the documentation? I've made a dump of "rpm -q -a | sort" on both machines, but the total number of differences is quite large, because I use the two machines for different purposes.

Any suggestions for further debugging? Would it help, if I post the output of "rpm -q -a | sort" for both machines? I could try to reinstall Fedora 29 from scratch on my laptop (rather than doing an upgrade from previous versions), but I would prefer a less invasive action, at least until the root cause has been found.

I've found the tmp folder that @spiro-trikaliotis mentions. Only one file was in there, it is attached here. (I've added the .txt extension to enable upload here on github without having to zip the file). Nothing special seems to be happening in line 254, as far as I can tell.

[sgmltmp.c64.1.txt](https://github.com/cc65/cc65/files/2670766/sgmltmp.c64.1.txt)

**Comment by spiro-trikaliotis** [comment]
Indeed, I cannot make sense from that file, either. I am sure there must be also another intermediate file. Or, the build process is completely different on that machine than on the machine I worked on.
I am sorry, I am out of ideas. :(

**Comment by greg-king5** [comment]
`PREFIX` is needed only if you do `make install`.

Tags in this project don't mean what they mean in other projects.  They don't mark official, debugged releases (they merely show where the version number changed).  You should get the latest revision of cc65; just use `git checkout master`.

"sgmltmp.c64.1" looks more like an output from nsgmls, instead of an input to it.

Our Makefile doesn't use the debug option.  Therefore, LinuxDoc-tools removes most of its temporary files.  If you want to see them, then you must change the Makefile.  There are two lines in the file that have the word `linuxdoc` in them.  Change `linuxdoc` to `linuxdoc -d`.

**Comment by MJoergen** [comment]
As @greg-king5 suggested, I've now done the following:

- `git checkout master`
- Updated doc/Makefile by adding -d after linuxdoc (two places). Then
- `make`
- `make doc`

This now gives the following output
```
[mike@granbo-4 cc65]$ make doc
  Loading /usr/share/linuxdoc-tools/fmt/fmt_html.pl
  Loading /usr/share/linuxdoc-tools/fmt/fmt_latex2e.pl
  Loading /usr/share/linuxdoc-tools/fmt/fmt_info.pl
  Loading /usr/share/linuxdoc-tools/fmt/fmt_txt.pl
  Loading /usr/share/linuxdoc-tools/fmt/fmt_lyx.pl
  Loading /usr/share/linuxdoc-tools/fmt/fmt_rtf.pl
Processing file ../doc/c64.sgml
DTD: linuxdoc
nsgmls:<OSFD>0:269:34:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:3:0: start tag was here
LinuxdocTools::process_file: Error when piping to:
| /usr/bin/sgmlpre output=html  | ( nsgmls -D /usr/share/sgml -D /usr/share/linuxdoc-tools -ifmthtml   || echo $? > /tmp/linuxdoc-tools.Nv8HHXANOd/nsgmls.error-flag ) > /tmp/linuxdoc-tools.Nv8HHXANOd/sgmltmp.c64.1
LinuxdocTools::process_file: nsgmls failed with exit status 1. Aborting ...
make[1]: *** [Makefile:37: ../html/c64.html] Error 25
make: *** [Makefile:18: doc] Error 2
```
Still only one file in /tmp/linuxdoc-tools*.

Looking at doc/c64.sgml I see that line 3 contains `<article>`, and line 269 begins with `<em>`. I tried first deleting line 269, but the same error occurred. I then tried deleting everything from line 269 to the end (except the last line `</article>`), and the error disappeared, at least for this file. The compilation proceeded and stopped on another file with the following error:
```
Processing file ../doc/tgi.sgml
DTD: linuxdoc
nsgmls:<OSFD>0:250:4:E: end tag for "VERB" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:248:13: start tag was here
nsgmls:<OSFD>0:250:4:E: end tag for "DESCRIP" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:240:0: start tag was here
nsgmls:<OSFD>0:250:4:E: end tag for "QUOTE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:239:0: start tag was here
nsgmls:<OSFD>0:250:4:E: end tag for "ARTICLE" omitted, but its declaration does not permit this
nsgmls:<OSFD>0:3:0: start tag was here
LinuxdocTools::process_file: Error when piping to:
| /usr/bin/sgmlpre output=html  | ( nsgmls -D /usr/share/sgml -D /usr/share/linuxdoc-tools -ifmthtml   || echo $? > /tmp/linuxdoc-tools.TWn8ESyOux/nsgmls.error-flag ) > /tmp/linuxdoc-tools.TWn8ESyOux/sgmltmp.tgi.1
LinuxdocTools::process_file: nsgmls failed with exit status 1. Aborting ...
make[1]: *** [Makefile:37: ../html/tgi.html] Error 25
make: *** [Makefile:18: doc] Error 2
```
Looking at line 248 of tgi.sgml indeed does contain the opening tag `<verb>`, and the corresponding closing tag is in line 252. I have no idea why the tool doesn't like line 250.

**Comment by MJoergen** [comment]
I just tried (in virtualbox) to make a clean install of Fedora 29. After doing
```
sudo dnf update
sudo dnf install linuxdoc-tools texinfo
```
and then running make doc, everything worked fine. It seems like a problem with my local installation. I'll reinstall Fedora 29 on my laptop, and hopefully this issue will disappear. If it works after reinstall, then I suggest this issue be closed as "cannot reproduce".

**Comment by musuruan** [comment]
Hi! I haven't tested this with the latest git checkout but when I packaged cc65 v2.17 for Fedora, I couldn't build the docs because of http://bugzilla.redhat.com/1489451. The workaround is not to install docbook-dtds.

BTW, you can find cc65 for Fedora here:
https://copr.fedorainfracloud.org/coprs/musuruan/cbm/

**Comment by MJoergen** [comment]
Following suggestion from @musuruan, I've uninstalled the docbook-dtds package on my laptop (where the make doc fails), and now it works! So it appears we've found the root cause (at least from cc65's perspective).

**Comment by spiro-trikaliotis** [comment]
@musuruan, thanks for this hint!

**Comment by groessler** [comment]
Anything left to do here?

**Comment by MJoergen** [comment]
No, please close this issue.
