### ISSUE TITLE
ATARI-CART: Where to start on Cartridge banking?

### ISSUE THREAD

**Issue by tschak909** [cc65/cc65#820]
Hello.

I have managed to successfully get PLATOTerm to squeeze into a 16K cart, and it works extremely well!

Most of the flash carts out there, as well as the ROM storage banks don't address the full 16K of ROM address space, but only use the left 8K, so I would need to split PLATOTerm into two banks. 

As I haven't done any bank switched software with CC65, where can I start? (not sure how I can figure out the best way to split code across banks)

-Thom

**Comment by oliverschmidt** [comment]
The most relevant starting point to banking with cc65 is https://github.com/cc65/cc65/blob/master/samples/overlaydemo.c

**Comment by groessler** [comment]
What are you referring to with "the ROM storage banks"?

I think Oliver's links should give you a head start. You have to make a new atari-cart.cfg which uses overlays. The MAIN memory will contain the bank-switching routines and be at the end of the memory (BFFF downwards), and the overlay (let's call them BANKx) files will contain the banked program codes. You will have to do manual steps after building to concatenate BANK0+MAIN and BANK1+MAIN to get two 8K ROM images.
How to spit the code? That's the most difficult part. You want each of BANKx filled to the max, while minimizing inter-dependencies (BANKx calls a function in BANKy). The linker map file ist your friend in this endeavour.

You wrote on AtariAge that you are really really really tight on memory. So it might not work with two banks. You were talking about flash carts, these should have more than two banks available.

Another idea, if the computer has 40K at least, take the existing 16K cart, write it to two banks on the flash cart, and copy one bank to the 8000...9FFF area at startup.

**Comment by tschak909** [comment]
I'd like to do the copy to ram under..but will need to think on how to do that... having a bit of an issue wrapping my head around the problem. -Thom

**Comment by groessler** [comment]
Depends on the available free memory space. You said something like 6 bytes left. That's too little.

But in general, I'd look into `libsrc/atari/cartstart.s` or `libsrc/atari/cartinit.s`. That are the entry points of the cartridge. Write a routine which banks in the 8000..9FFF bank, copies its contents to 8000..9FFFF, banks in the other A000..BFFF bank again. Add in cartstart or cartinit a routine which is run as the very first thing, to copy the other routine to RAM and call it. Since the 8000 area probably has the screen buffer, in your "copy8000" routine set RAMTOP/MEMTOP to 8000 and issue a "graphics 0" call to relocate the screen.

**Comment by groessler** [comment]
And, yes, use the `.org` directive to compile the "copy8000" routine for the address in RAM you are going to copy it to.
