### ISSUE TITLE
[question] How to align Assembly code and have it work with the linker?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#883]
I have a new project with some other people:
https://github.com/Fabrizio-Caruso/C64_Multiplexer_C_LIB
whose purpose is to make a 32 sprite multiplexer usable through some C APIs.

I am trying to compile/link the initial C code and Assembly code where some data has to be aligned at $40, i.e., at the end the file has:
```
...
    .ALIGN $40
SPRITE_GFX:
    .RES 64,255                       
...
```

But I get:
```
ld65: Warning: ./cfg/c64_multiplexer.cfg(23): Segment 'CODE' isn't aligned properly; the resulting executable might not be functional.
```

How can I fix this problem?

**Comment by greg-king5** [comment]
> ```asm
> ...
>     .ALIGN $40
> SPRITE_GFX:
>     .RES 64,255                       
> ...
> ```
> But, I get:
> ```
> ld65: Warning: ./cfg/c64_multiplexer.cfg(23): Segment 'CODE' isn't aligned properly; the resulting executable might not be functional.
> ```
> How can I fix this problem?

Read https://cc65.github.io/doc/ld65.html#ss5.7

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 I don't find any reference to .ALIGN Assembly directive and how to make it work with the linker. Is it possible?
Are you suggesting this is impossible and I should instead create a section in the cfg file?

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 I have this problem only if I use .ALIGN in Assembly.
What does .ALIGN do? I just want that Assembly portion moved at the next $40-byte boundary and have the hole filled with something. Do I need to go through the linker configuration also for this?

I am trying to guess what @greg-king5 is suggesting but I am not sure.

**Comment by oliverschmidt** [comment]
I don't see that there's any guesswork necessary. The doc @greg-king5 pointed to says "Specify "align = num" to request this feature."

So: Yes, you need a custom linker config to align something.

**Comment by greg-king5** [comment]
Read the second half of the second paragraph.  It starts with "Alignment is always needed if you have used the `.ALIGN` command in the assembler."

The change can be as simple as
```ini
    LOWCODE:  load = MAIN,     type = ro,  optional = yes;
    CODE:     load = MAIN,     type = ro,  align    = $40;
```
ld65 might put some $00 bytes between the `LOWCODE` and `CODE` segments.  If you want to know how many bytes, then look at the segment list in the map file.

**Comment by Fabrizio-Caruso** [comment]
Thanks @greg-king5 ! 
I clear don't understand why the segment has to be aligned if I just want a small portion of a small generated binary to be aligned.

I may have misunderstood the meaning of .ALIGN. I thought it aligns what follows to a given boundary but filling the empty part with somw default value. The containing segment does not have to be aligned.

**Comment by mrdudz** [comment]
thats because the .align directive works relative to the segment address, not the absolute address. i find that a bit annoying and mostly unusable too. odd design choice :)

**Comment by oliverschmidt** [comment]
Hm...

* The only one who creates content (like "filling the empty part with some default value") is the assembler.
* The only one who knows about absolute addresses is the linker.
* The linker runs after the assembler.

I must admit that I don't see an odd design choice here.

**Comment by mrdudz** [comment]
uhm, are you sure what you say is true? i dont think thats exactly how it works. the assembler doesnt even know how many fill bytes to insert when it encounters an align directive, for that it would have to know where in a segment a piece of code goes to.

**Comment by oliverschmidt** [comment]
> uhm, are you sure what you say is true?

I really think so.

> the assembler doesnt even know how many fill bytes to insert when it encounters an align directive, for that it would have to know where in a segment a piece of code goes to.

I thought/think that the assembler always presumes that the alignment of the segment is at least as large as the largest alignment the user asks for with `.align`. Just in the same way the compiler always presumes that malloc() returns memory with an alignment large enough to access all data types. Based on that presumption it creates paddings in structs.

The assembler places that presumption made in some metadata it generates for the linker. And if the segment placement the user asks for in his linker config doesn't meet that presumption one sees the warning in question.

My perspective at least matches very well the statements in the doc:

_The alignment of a segment must be equal or greater than the alignment used in the .ALIGN command. The linker will check that, and issue a warning, if the alignment of a segment is lower than the alignment requested in an .ALIGN command of one of the modules making up this segment._

> [...] you pretty much always want to use .align to align to a physical address. i cant think of any other usecase at least.

ACK.

> and it works like that in any other assembler i have used, including those that use linkers

I might be interesting to learn how it is done. I can imagine one way: The linker sort of "implicitly adds the necessary align attribute to the segment" in question. I imagine that there might be users considering such an "auto-alignment" surprising. But most users might like it.

However, this doesn't end with the segment. Rather the memory area needs to start on an address matching the alignment requirements of its segments.

So at least from my current POV this is not the question of a general design choice (I don't see viable alternatives to the current design). But rather the question of an "auto-alignment" feature (based on the current design).

**Comment by groessler** [comment]
> you pretty much always want to use .align to align to a physical address

Not really. Sometimes you want to alight to a page boundary so that a following loop construct doesn't cross a page boundary. BNE and friends take one additional cycle if the destination is on another page.

**Comment by oliverschmidt** [comment]
I think this is a misunderstanding. The example you give (alignment to page boundary) is still an alignment to a physical address (in contrast to e.g. an alignment to a segment start).

**Comment by groessler** [comment]
Hmm. Probably. With physical address it somehow associated some hardware requirements (as they are usual on Atari).
I, too, cannot see any use case to align to "segment start".

**Comment by groessler** [comment]
Regarding .align, consider this code snippet:

```
.code

.import a_global

;.export foo
foo:
        jsr a_global
        beq bar

.align $40

bar:    rts

.end
```

The ca65 listing file shows that the address of `a_global` isn't known ("rr" in the bytes), but suggests that the "bne" destination is hard coded. But, if you look at a hexdump of the resulting object file (unfortunately we don't have a tool to disassemble the code of an object file), it seems that in the object file just the need for the alignment is recorded, no filler bytes or an absolute destination of the branch.

Therefore the linker could, as it knows the actual addresses where the code will finally reside, just honor the .align directive, independently of the alignment of the segment where the code is in. I, too, don't understand the need to have the segment itself aligned in this case. But, sure, maybe there's a reason I'm not aware of. We need to look at the linker code...

**Comment by mrdudz** [comment]
I am pretty sure it can be made to work "as expected". it'd be really odd if not :)

**Comment by laubzega** [comment]
> [snip] But, if you look at a hexdump of the resulting object file (unfortunately we don't have a tool to disassemble the code of an object file), it seems that in the object file just the need for the alignment is recorded, no filler bytes or an absolute destination of the branch.

What's recorded in the .obj depends on whether the filler byte is already known, i.e. if it's been specified as an argument to .ALIGN. If so, the .obj contains the actual bytes. Otherwise, the information is left for the linker that so-and-so many bytes are supposed to be inserted, since the linker is the one that knows the filler byte.


> Therefore the linker could, as it knows the actual addresses where the code will finally reside, just honor the .align directive, independently of the alignment of the segment where the code is in. I, too, don't understand the need to have the segment itself aligned in this case. But, sure, maybe there's a reason I'm not aware of. We need to look at the linker code...

The linker could not, because the linker has no information about the required alignment anymore - just the number of bytes to insert, which is not the same. Why is it done this way is really unclear. I mean, this whole "alignment from the beginning of the segment" concept. Is there really a use for it? There is so much code dealing with it, and so much memory potentially wasted ("the alignment of the segment must be a multiple of each of the alignment factors") that there is a dedicated warning and a flag for silencing it, but the purpose and benefits are lost on me.

One approach would be to just carefully delete it all and then simply implement a regular alignment as it works in any other system known to mankind. Unfortunately, probably something depends on this weirdness and will mysteriously start failing in some unexpected way, and thus we have to live with it forever.

The alternative is to add a new command (.ALIGNSANE? .ALIGNLOCAL? .ALIGNMENT? other ideas?), create a new Fragment with appropriate information, modify linker to grok this Fragment and on the fly decide the number of bytes to output.

How about that?

**Comment by mrdudz** [comment]
I'd be totally willing to merge a PR that removes this "alignment relative to segment start" nonsense and replaces it with proper "alignment to memory address". It's one of my biggest griefs with the toolchain, its annoying as hell.

**Comment by laubzega** [comment]
Well, turns out that this won't work either. cc65 determines the length of object data during assembly and there seems to be no way to modify it later without potentially breaking all references within given object file. Even if some sort of second pass could be rolled out to fix it by redoing relocations after alignment-forced resizing, this still leaves relative references unsolved. Relative references are also the reason why dynamically creating anonymous segments at each .ALIGN to introduce positioning flexibility won't work, as there are no relative references possible between segments. Not being able to BRA around aligned stuff would be laughable.

I will sleep on it, but right now it looks like "alignment relative to segment start" is by far the simplest way of providing some makeshift ALIGN functionality within the confines of cc65's design. That's why it is here. :/


![image](https://user-images.githubusercontent.com/5245003/205848750-963ebdc3-b43d-4f91-942e-67ce2b09967f.png)
