### ISSUE TITLE
__asm__()-referenced code-labels are generated for only branches and jumps

### ISSUE THREAD

**Issue by Wrathchild70** [cc65/cc65#897]
Example:
```c
#pragma bss-name (push,"ZEROPAGE")
static unsigned char *srcptr, *dstptr;
#pragma bss-name (pop)

#define COPY_LEN	16

void main(void)
{
	asm("lda %v", srcptr);
	asm("sta %g+1", s2b_copy_from);
	asm("lda %v+1", srcptr);
	asm("sta %g+2", s2b_copy_from);
	
	asm("lda %v", dstptr);
	asm("sta %g+1", s2b_copy_to);
	asm("lda %v+1", dstptr);
	asm("sta %g+2", s2b_copy_to);

	asm("ldy #%b", COPY_LEN-1);
s2b_copy_from:
	asm("lda $FFFF,y");
s2b_copy_to:
	asm("sta $FFFF,y");
	asm("dey");
	asm("bpl %g", s2b_copy_from);
}
```
Becomes
```asm
;
; File generated by cc65 v 2.17 - Git 5c8854f
;
	.fopt		compiler,"cc65 v 2.17 - Git 5c8854f"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main

.segment	"BSS"

.segment	"ZEROPAGE"
_srcptr:
	.res	2,$00
_dstptr:
	.res	2,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     _srcptr
	sta     L0008+1
	lda     _srcptr+1
	sta     L0008+2
	lda     _dstptr
	sta     L0013+1
	lda     _dstptr+1
	sta     L0013+2
	ldy     #$0F
L0008:	lda     $FFFF,y
	sta     $FFFF,y
	dey
	bpl     L0008
	rts

.endproc
```
Therefore, `L0013:` is not being output.

**Comment by groessler** [comment]
Where in your C code are `s2b_copy_to` and `s2b_copy_from` defined?

**Comment by groessler** [comment]
Sorry, ditch my comment. I'm bilind :-)

**Comment by oliverschmidt** [comment]
@greg-king5: Just to avoid misunderstandings: The issue is present when calling cc65 without any optimization option.

In the example given by the OP the label `L0008` is there (as desired) and the label `L0013` is missing. The difference comes from the fact that `L0008` is referenced by a branch instruction while `L0013` is only referenced by a "data" instruction . So it seems that there's some "unused label cleanup" step that doesn't take self modifying code into account - as such code isn't generated by the compiler.

This knowledge leads btw. to the obvious workaround to add a never reached branch instruction referencing the label in question.

**Comment by greg-king5** [comment]
> That knowledge leads, btw., to the obvious workaround to add a never-reached branch instruction referencing the label in question.

That dead code might be removed by the optimizer.  A safer workaround is a branch that is executed, but never jumps.  In the example code, the last `asm()` line could be duplicated, but with the second label.  When the first `bpl` falls through, the second one also would fall through.

**Comment by mrdudz** [comment]
due to #1447 - shouldnt this one get closed?

**Comment by oliverschmidt** [comment]
Yes, indeed.
