### ISSUE TITLE
[question][Atari5200] What is the cleanest way to implement now missing CYAN, BROWN, etc. colors?

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#901]
After recent changes my universal game no longer compiles for the Atari 5200 target because of missing definitions for colors such as CYAN and BROWN.
How do I get those colors back into my game?
What is the cleanest solution?

**Comment by oliverschmidt** [comment]
As far as I understand the correct solution is to include `_gtia.h` and use `GTIA_COLOR_...` macros. But maybe @groessler can improve on this information.

**Comment by Fabrizio-Caruso** [comment]
I saw a looong discussion on this but I could not understand why the ATARI5200 is now a unique target with just four conio colors... and I cannot understand why colors are not defined as GTIA_COLOR...
Anyway your suggestion gets my game to compile again. I hope the GTIA_COLOR are the same as the ones in Atari-8-bit target.

**Comment by groessler** [comment]
> ...because of missing definitions for colors such as CYAN and BROWN.

Please state exaclty what you mean when creating an issue. I don't know of any `CYAN` and `BROWN` defines for any Atari traget. I know `COLOR_CYAN` and `COLOR_BROWN`, and `GTIA_COLOR_CYAN` and `GTIA_COLOR_BROWN`.
The former are conio defines, the latter are hardware defines.

> As far as I understand the correct solution is to include `_gtia.h` and use `GTIA_COLOR_...`

`_gtia.h` is not intended to be included directly. If one includes `atari.h` or `atati5200.h` the `_gtia.h` file will be included as well.

> I saw a looong discussion on this but I could not understand why the ATARI5200 is now a unique target with just four conio colors...

So I guess you "saw" the long discussion, but didn't "read" the long discussion. If you go through the discussion you'll notice that the change was done in order to make the `conio` implementation constistent in itself. (I myself had reservations at the beginning, but finally came to the conclusion that this is a better overall solution.)

> with just four conio colors...

One still can use five colors by writing into the hw registers directly. In the same way one can redefine the four default colors. The `COLOR_xxx` values used as parameters to `textcolor()` then just become a "placeholder" for what is set in the hw color registers.

> and I cannot understand why colors are not defined as GTIA_COLOR...

They **are** defined as `GTIA_COLOR_...` defines, just not all of them are available as `COLOR_xxx`. The conio color defines `COLOR_xxx` include just those which are used by conio as defaults.

> I hope the GTIA_COLOR are the same as the ones in Atari-8-bit target.

Yes.
And, remember the `GTIA_COLOR_xxx` defines are just a subset of the possible colors on 5200. They are chosen to more or less match the C64 `COLOR_xxx` defines. But one can use any available color,
