### ISSUE TITLE
[feature request] Option to have global variables in zeropage

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#917]
Global variables in zeropage can produce more than >10% speed-ups. This can be implemented currently by a cumbersome procedure:

1. declaring then as extern 
2. using the zpsym pragma 
3. and then linking a .s file with their actual location in zero-page

It would be nice to trigger this behavior with a new option (-Oz ?) that would just take the first global variables in the order in which they are declared and map them in zero-page locations that are usually available for C-only projects for each specific target (or use a target-specific config file for this). 

An example of a nice >10% speed-up produced by this optimization is testable in my project:
https://github.com/Fabrizio-Caruso/Primitive-Pythagorean-Triples

Remark: ANSI C does not allow the register qualifier on global variables. So we cannot have this behavior as a result of the register qualifier on global variables.

**Comment by oliverschmidt** [comment]
Have you already checked how the performance looks like when you use register variables in compute_new_triple() ?

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt as I wrote in my remark this is not possible in ANSI C

**Comment by oliverschmidt** [comment]
I was talking about register variables _in_ that function. You see, turning global variables into local variables of that function and then attributing them as register. Hopefully this is explicit enough ;-)

**Comment by Fabrizio-Caruso** [comment]
@oliverschmidt I need the values of some variables to be visible outside the scope of the function. So I either introduce parameters or I keep them as global variables.
Some other variables can be made local and only for these I could use the register qualifier.

**Comment by oliverschmidt** [comment]
Copying global variables to register from/to register variables might be a viable option. Function parameters and the return value can be register too.

**Comment by Fabrizio-Caruso** [comment]
Tests:
No zero page + global variables: 0.566
Register variables only for temporary (localizable) variables: 0.633
Zero page for global variables: 0.516

Zero page for global variables is the fastest and simplest solution that requires no tinkering with the code. It would be nice to trigger this without having to use extern+zbsym+.s file with defs.

**Comment by oliverschmidt** [comment]
Thanks for the numbers. "It would be nice" is very well phrased ;-)

**Comment by Fabrizio-Caruso** [comment]
If I try to use only register variables by converting the global ones into register parameters to pass, I get an even worse time: 0.683.

So, my little math exercise discovers two unexpected behaviors:
- zeropage for global variables provides big speed-up and it is a real pity CC65's optimizer is not doing this and cannot do this without the extern/zbsym/.s defs contortion
- introducing dummy variables triggers a better optimization (discussed in #916, which could even be a bug maybe)

I am not a compiler expert and I don't want to push anyone. I can happily live without a -Oz option that could do this sort of trivial and useful optimization because I know how to achieve this result.
I suspect that this could be implemented in a not too complicated way by those who have already touched the optimizer. Am I wrong?

**Comment by mrdudz** [comment]
making this a compiler option doesnt make a lot of sense imho. there arent a lot of free zeropage locations in a non trivial program to begin with. even less so when looking at all targets. and the compiler cant really decide what variables make most sense in zeropage either.

you'll just have to live with the fact that with contrained targets you'll have to do this sort of optimizations manually (and the result will also always be better than what the compiler could do)

**Comment by Fabrizio-Caruso** [comment]
@mrdudz  why? I am only proposing this for global variables (which cannot be optimized with the register keyword). The compiler could just do a very mechanical optimization: take the first N global variables and just map them into zeropage locations (at either per-target hard-coded locations or provided by the user). This would bring 10-15% more speed in many cases with a simple optimization.
People complain about how slow CC65 is and we have a simple solution on how to speed it up significantly in many use-cases (all use-cases with heavily used global variables).
I am promising to use an option to trigger it and not have it by default.

**Comment by mrdudz** [comment]
> This would bring 10-15% more speed in many cases with a simple optimization.

I dont see this happening in a non trivial program. It might apply in small things like your example, sure

**Comment by Fabrizio-Caruso** [comment]
@mrdudz  other people have reported having to use the same contorted trick to achieve these speed-ups. You will get similar speed-ups in non-trivial programs as long as they heavily use global variables. It all depends on how much your code depends on those variables. CC65 projects often use global variables extensively becauee of local variables and parameters are slow.
If your code does not use global variables extensively, this optimization won't make yout code slower nor bugger. You will just get a small speed-up.

**Comment by mrdudz** [comment]
Non trivial programs will use so many of those variables, that having a few of them in zeropage wont have a lot of impact. It might work for a few special cases - but then you are again better off choosing yourself which variables are the ones where you'd benefit most. I dont consider it a "contorted trick" either - its just how you work with C on constrained 8bit systems.

**Comment by Fabrizio-Caruso** [comment]
@mrdudz that is why I wrote "first global variables" so that the user could tell the optimizer which variables are more heavily used. Other solutions are possible like for example an option in the linker cfg.

Having the compiler use more the zeropage seems like a simple solution to me. Using pragma,extern a Assembly definitions is an overkill for something that could be triggered by a compiler option.
It seems an easy trick with a big win and little cost for the compiler's coders here.
I have read but I am not sure that GCC6502 heavily uses zeropage as extra virtual registers. KickC may be doing something similar. I have the impression that we could exploit zeropage more in CC65.

**Comment by mrdudz** [comment]
"first global variables" only works with a trivial program to begin with. once you have a bigger project with a dozen files and hundreds of variables, it will be mostly random and pointless to put "the first global variables" into zeropage.

**Comment by Fabrizio-Caruso** [comment]
@mrdudz  it would be up to the user to declare the most used variables first or use some other more conveninent solution than the current one made of 3 actions (extern + zbsym + .s def's)

**Comment by mrdudz** [comment]
again: that doesnt work with a huge project. "declare most used variables first" only works when the entire code is in one file.

IMHO the proper (better than now) solution would be having a pragma that works without this extern declaration. However, that it isnt already like this tells me that this cant be easily done :)

**Comment by greg-king5** [comment]
> IMHO, the proper (better than now) solution would be having a pragma that works without this extern declaration.

I prefer to go in the other direction:  replace the pragma with a `__direct__` qualifier.  It would be the eight-bit address companion of the `__near__` (16 bits) and `__far__` (24 bits) qualifiers.

**Comment by groessler** [comment]
@Fabrizio-Caruso, I don't understand why it is "overly complicated" to put variables into the ZP. See this

```
#pragma bss-name (push, "EXTZP")
unsigned char zpvar;
#pragma zpsym("zpvar")
#pragma bss-name (pop)

unsigned char normvar;

unsigned char ret_zpvar(void)
{
        return ++zpvar;
}

unsigned char ret_normvar(void)
{
        return ++normvar;
}
```

compiles to

```
;
; File generated by cc65 v 2.18 - Git e34ee329
;
        .fopt           compiler,"cc65 v 2.18 - Git e34ee329"
        .setcpu         "6502"
        .smart          on
        .autoimport     on
        .case           on
        .debuginfo      off
        .importzp       sp, sreg, regsave, regbank
        .importzp       tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
        .macpack        longbranch
        .exportzp       _zpvar
        .export         _normvar
        .export         _ret_zpvar
        .export         _ret_normvar

.segment        "BSS"

.segment        "EXTZP"
_zpvar:
        .res    1,$00
.segment        "BSS"
_normvar:
        .res    1,$00

; ---------------------------------------------------------------
; unsigned char __near__ ret_zpvar (void)
; ---------------------------------------------------------------

.segment        "CODE"

.proc   _ret_zpvar: near

.segment        "CODE"

        ldx     #$00
        inc     _zpvar
        lda     _zpvar
        rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ ret_normvar (void)
; ---------------------------------------------------------------

.segment        "CODE"

.proc   _ret_normvar: near

.segment        "CODE"

        ldx     #$00
        inc     _normvar
        lda     _normvar
        rts

.endproc
```

Put them explicitly into a ZP segment and add the pragma zpsym. I don't consider this undue effort.
You don't need `extern` and you don't need an asm file. Or am I missing something? (Btw., I don't understand why people are afraid of using asm source files for variable declarations. You don't need to understand assembler for that.)

With this the programmer has explicit control over which vars go to ZP.

And, what I haven't heard in the discussion so far is the question how the ZP vars get initialized at program startup. They aren't initialized by the startup code (AFAIK), you have to do that manually.

**Comment by Fabrizio-Caruso** [comment]
@groessler thanks! Your solution works if those 6 locations are enough and they are not needed elsewhere in local functions where the register keyword is used.
In all other cases more zero page locations are necessary.

**Comment by groessler** [comment]
That's a totally different story.

**Comment by groessler** [comment]
What 6 locations are you talking about?

**Comment by mrdudz** [comment]
the default EXTZP, i guess

**Comment by groessler** [comment]
There it depends very much on the target. Anyway, there are target with rather littel ZP space available and targets with more. Needs to be considered if one wants to make a cross-platform program.

**Comment by Fabrizio-Caruso** [comment]
@groessler, indeed that is why the syntax should be agnostic of target and of the number of bytes available in ZP.
Whatever solution is chosen, it should not break code that uses the current register qualifier and it should not break the binary if the implicitly or explicitly selected global variables in ZP does not fit in ZP of a specific target.
That is why a compiler's option could do the job and would not pollute the code with pragma's, externs or other qualifiers.

**Comment by mrdudz** [comment]
the compiler doesnt know how many zp space is available

**Comment by Fabrizio-Caruso** [comment]
@mrdudz how does the register keyword work then? Whatever solution is chosen, it should just map some of the global vars into ZP. The selection should as simple as possible or implicit (the order).

**Comment by mrdudz** [comment]
the register keyword works per function, values are copied to temporary zp locations when entering a function (or a block perhaps? i dont recall exactly). its also a good example of why what you want doesnt really work - try just declaring everything as register variables and see what happens.

however, we are moving in circles. "just map some of the global vars into ZP" isnt something that can be easily done. nor does it make a lot of sense.

**Comment by groessler** [comment]
> indeed that is why the syntax should be agnostic of target and of the **number of bytes available in ZP**

I presume, you are talking about your idea of automatically (if the compiler option is given) put the first  N global vars into zero page? Otherwise it wouldn't make much sense to me.

@mrdudz already told you that the compiler doesn't know how much ZP space is available. It probably could be told about that, 

How should the initialization of the ZP vars work? The startup code would need to be extended to do .data and .bss initialization for ZP vars. This would consume space for every program, even if it doesn't use ZP vars.

So sure, everything could be done, given enough time and resources. Who should do it? I guess no one here wants to do the work, so it would be up to you.

And, personally, I (as programmer) want to keep my hands on what should go to the ZP, and don't want the compiler do to these things automatically.

\<joke\>Since over twenty years I'm researching how to implement a program, a GUI program, with just one button labeled "Do what I want". It's difficult and I haven't proceeded very far.\</joke\>

**Comment by Fabrizio-Caruso** [comment]
One more example where just 3 global variables in zeropage provide a significant boost from 2.0 seconds to 1.75 seconds:
https://github.com/Fabrizio-Caruso/Sieve

**Comment by groessler** [comment]
So, put them into the ZP. There are ways to do this already.

**Comment by Fabrizio-Caruso** [comment]
Sure, but if this is good most of the time, it would make sense to have the compiler/linker/optimizer do this for you and let you keep standard clean C code with no pragmas and no extra Assembly files. I am going to test if this is beneficial in Cross Chase, which is several thousands lines of code.

**Comment by groessler** [comment]
Fabrizio, please see this from a POV of cc65:

Before I get another rebuke from Oliver, let's it phrase like this:

"I don't think your idea of automatically putting the first N global vars into zero page is a good idea."

Why:

- previously mentioned, "first N global" vars is not really defined if multiple source files are in the game
- some targets have more, some have less ZP space available. So Joe Average Programmer compiles his proggie for targets A and B. A runs much faster, but B is slow lke hell. A has much more ZP space available as B. Can this person be expected to know that the option you intend to introduce - automatically put globs into ZP space - is so much target dependent? Even if he knows, there's no clear indication in the source code what goes to ZP and what not. He has to manually count his "first" X globals to find out what will go into ZP. (Or use a linker map file. Still an annoying manual "parse and match" process.) 
- the whole thing needs to be implemented, with (in my eyes) not much benefit
- a generic "attribute" to the var also doesn't work, because you still have to make it target dependent (in your source code) for targets with too little ZP space for what you want to use

So, all in all, it's better the programmer does this manually, and in turn knows beforehand what can be expected in terms of speed gain on which target.

And this can be done right now, with the current version, without involvement of assembler files.

My 2¢

**Comment by Fabrizio-Caruso** [comment]
@groessler you are probably right and I am not sure about the best specific solution. I am just proving one point: using zeropage in a straightforward way in multiple cases produces a 10-15% speed-up with little effort and "it looks" it could be automatized.
On the other hand, people complain about CC65's performances and it looked to me that showing a simple trick could encourage people with more experience to come up with some smart implementation ideas.
It seems that other compilers are using zeropage more in order to squeeze extra performance in both speed and space: https://github.com/itszor/gcc-6502/pull/6

**Comment by silverdr** [comment]
> So Joe Average Programmer compiles his proggie for targets A and B. A runs much faster, but B is slow lke hell

Not advocating anything here but trying to put myself into Joe's shoes, I would probably be happy that the optimiser did "something" to make the PRG run much faster on some/one target (A), without me knowing anything else than C lang. Like about ZP etc.

**Comment by groessler** [comment]
> It seems that other compilers are using zeropage more in order to squeeze extra performance in both speed and space: itszor/gcc-6502#6

If you read PR#6 linked above carefully, you'll notice that the ZP change wasn't merged.

**Comment by wjakobczyk** [comment]
> I don't understand why it is "overly complicated" to put variables into the ZP. See this

I have tried this solution and it does not compile valid zp code. The assembly seems ok, but the machine code generated for accesses to zpvar is not using zero-page addressing:
```
    206F: A2 00     _ret_zpvar LDX #$00
    2071: EE 9C 00          INC _zpvar
    2074: AD 9C 00          LDA _zpvar
    2077: 60                RTS
    2078: A2 00     _ret_normvar LDX #$00
    207A: EE 0D 21          INC _normvar
    207D: AD 0D 21          LDA _normvar
    2080: 60                RTS
```
I use cl65 V2.18 - Git e2c66486 with options:
```
cl65 -g -Osir -r -t atari -Wl --dbgfile,test_zp.dbg test_zp.c -o test_zp.xex
```

**Comment by acqn** [comment]
@wjakobczyk You need somehow to tell ca65 about the address size.
I made an extention in my personal fork of cc65 for this:
```c
#pragma bss-name (push, "EXTZP", "zeropage") // new option to declare the address size
unsigned char zpvar;                         // no need for #pragma zpsym("zpvar")
#pragma bss-name (pop)

unsigned char normvar;

unsigned char ret_zpvar(void)
{
    return ++zpvar;
}

unsigned char ret_normvar(void)
{
    return ++normvar;
}
```
compiles to
```
;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.exportzp	_zpvar
	.export		_normvar
	.export		_ret_zpvar
	.export		_ret_normvar

.segment	"BSS"

.segment	"EXTZP": zeropage
_zpvar:
	.res	1,$00
.segment	"BSS"
_normvar:
	.res	1,$00

; ---------------------------------------------------------------
; unsigned char __near__ ret_zpvar (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ret_zpvar: near

.segment	"CODE"

	ldx     #$00
	inc     _zpvar
	lda     _zpvar
	jmp     L0003
L0003:	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ ret_normvar (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ret_normvar: near

.segment	"CODE"

	ldx     #$00
	inc     _normvar
	lda     _normvar
	jmp     L0005
L0005:	rts

.endproc

```
and it does generate machine code using zero-page addressing.

**Comment by acqn** [comment]
So... is there any interest in such a way as in my fork to deal with this issue? Is the design choice OK? Is the new #pragma syntax subject to bikeshedding?

**Comment by mrdudz** [comment]
I think this is a valid and generic approach to the problem

**Comment by oliverschmidt** [comment]
> > Is the new #pragma syntax subject to bikeshedding?

> I think this is a valid and generic approach to the problem

Me too! I'd be in general happy to merge such a PR :-)

**Comment by Fabrizio-Caruso** [comment]
@acqn this is very good! Thanks! I was also asking for something slightly different.
I was asking to have the compiler/optimizer figure out some global variables to store in zero page.
This would produce better code without the pragmas on generic C code.

**Comment by oliverschmidt** [comment]
Just to make sure there are no misunderstandings: At least based on my current understanding of how such a feature would work I don't see me merging a PR implementing it.

**Comment by acqn** [comment]
I had this extension just for my private project and it fullfilled all needs back then, but when it comes to the upstream, much more has to be considered. What about other targeted platforms?

This unavoidably raises the question about what numeric addresses belong to the zeropage on various targets. While I am not aware of all of the, open Issues such as #319 indicate that not all platforms map the zeropage at #$0000. What shall be done to deal with them on the cc65's end?

Moreover, since I am parsing the instructions arguments to extract the names of symbols instead of strcmp'ing the strings (which is insufficient as the symbols may appear in "zp+1" etc. forms), it makes me wonder how "feature-complete" this argument parser is supposed to be  (which also affects Issue #897 that requires parsing the arguments as well). Is it sufficient to be to parse all possible arguments possibly generated by the cc65 C compiler except for the inline asm statements (which may be a hard problem for #897 as that is the very asm)?

**Comment by oliverschmidt** [comment]
> While I am not aware of all of the, open Issues such as #319 indicate that not all platforms map the zeropage at #$0000. What shall be done to deal with them on the cc65's end?

It would be totally fine with at least me if the feature in question just wouldn't work with such targets. If someone "fixes" https://github.com/cc65/cc65/pull/319 he'll have to take care of producing an error if the user tries to use the feature.

> Is it sufficient to be to parse all strings possibly generated by the cc65 C compiler except for the inline asm statements?

I personally would say 'conceptually yes'. However, my question is: What happens if someone does use inline assembly?

**Comment by acqn** [comment]
> 
> 
> What happens if someone does use inline assembly?

There are several possible ways when it comes to inline assembly.
- Optionally, get the symbol names directly before they are "printed" into the asm string as the "%" parameters.
- Optionally, try with the argument parser when creating the code entries. If it can't fully understand the argument string, leave it as is.
- At last, if there is no successfully parsed info about the symbol names, just do what is currently done with the argument string as a whole for inline assembly.

It would be funny if the first option is chosen: the inline assembly part would know about the symbol/type info better than the C part could.

**Comment by oliverschmidt** [comment]
My problem is that I'd like to give you all necessary input and feedback - but I'm afraid I can't follow you :-(

I seem understand that we're talking about global variables living in the zero page. And the general issue is that we want to have cc65 take advantage of that fact when it comes to accessing those variables.

And here it's about user writing inline assembly accessing those variables, right? My question "What happens if someone does use inline assembly?" was extremely unclear but was actually meant as "Is there something worse that can happen beyond inline assembly not taking advantage at all of the fact that those variables live in the zero page?" or from yet another perspective: "When talking about inline assembly: Is this only about potentially missed opportunities, or about incompatibility - resulting in wrong code generated?".

Presuming that we're "only" talking about inline assembly not taking advantage of variables in the zero page I'm fine with any solution you come up with. The fact that inline assembly doesn't play well with the compiler optimization makes inline assembly a pretty weak feature anyhow: You need to disable the compiler optimizer to use it. This prohibits its usage in large C functions. And small C functions can as well be replaced with "true" assembly code.

**Comment by acqn** [comment]
My extension is actually a combination of three:
- Make it possible to specify the address size of a segment in the generated .s and nothing else.
- Make variables on a ":zeropage" segment recognized as SC_ZEROPAGE thus they can be exportzp'ed without the zpsym prgma.
- Recognize ZP variables when parsing instruction strings and use the appropriate ZP addressing modes as an optimization.

The parsing problem only affects the last part. If parsing fails, it does what it would be done without this extension.

> Is there something worse that can happen beyond inline assembly not taking advantage at all of the fact that those variables live in the zero page?

That's my biggest concern about this. AFAIK, no, as long as the user does it correctly (e.g. not overflowing the ZP).

> When talking about inline assembly: Is this only about potentially missed opportunities, or about incompatibility - resulting in wrong code generated?

I haven't been able to come up with a correct inline assembly code snippet that fail because of this. All I see so far is missed opportunities. It is much more easy to break the other existing optimization steps with specifically crafted inline assembly.

**Comment by oliverschmidt** [comment]
Thanks for the comprehensive explanation. I'd say go forward even if there's a risk of breaking obscure/invalid inline assembly.
