### ISSUE TITLE
MVN/MVP require non-standard syntax in v2.18

### ISSUE THREAD

**Issue by fadden** [cc65/cc65#926]
As noted in issue #925, the syntax for MVN/MVP have changed from v2.17.  In particular, something like:

    MVN 1,2

used to generate `54 01 02` (reversed).  Instead of generating `54 02 01`, v2.18 generates `54 00 00`, because operands not prefixed with '#' are treated as 24-bit values, and the bank byte is extracted.

As I noted in a comment in #925, this means there is no longer any way to write MVN/MVP that works in all four cross-assemblers supported by SourceGen. Given two labels with 24-bit addresses:

`mvp 1, 2` - works in Merlin 32, 64tass, ACME; generates zeroes in cc65 v2.18
`mvp #1, #2` - works in Merlin 32, 64tass, cc65; errors in ACME
`mvp label1, label2` - works in Merlin 32, cc65; errors in 64tass, ACME
`mvp #label1, #label2` - works in Merlin 32; errors in 64tass, ACME, cc65

The recommended form in the 65816 spec sheet does not use immediate mode syntax. 
(See e.g. https://westerndesigncenter.com/wdc/documentation/w65c816s.pdf, Table 6-2 on page 47)  The COP instruction is another example of something that takes an 8-bit constant operand but doesn't use '#'.

Note I'm not arguing what the most logical or sensible way of handling block move syntax is.  I'm arguing that there's a standard way of handling it, and diverging from that is problematic.

**Comment by oliverschmidt** [comment]
I hope you can understand that I don't classify this issue as a bug...

**Comment by greg-king5** [comment]
> The recommended form in the 65816 spec. sheet does not use immediate mode syntax.
> (See, e.g., https://westerndesigncenter.com/wdc/documentation/w65c816s.pdf, Table 6-2 on page 47.)

That table shows the syntax, but not the semantics.  It doesn't say what the symbol `d` means.  Is it a bank number; or, is it a direct-page address?  The book, _Programming the 65816_, says that it's an address.  Page 53 of _[Software Development System Assembler⁄Linker⁄Librarian](https://westerndesigncenter.com/wdc/documentation/Assembler_Linker.pdf)_ shows both immediate and address syntaxes.

Therefore, I claim that ca65 doesn't deviate from the recommended standard.
> The `COP` instruction is an example of something that takes an 8-bit constant operand; but, doesn't use `#`.

That's because immediate mode is the only mode that it accepts -- some syntax isn't needed to tell an assembler what mode to use.  But, ca65 accepts two operand modes for `MVN` and `MVP`; therefore, we do need some syntax to tell an assembler which mode.

**Comment by fadden** [comment]
I sat here coming up with ways to argue my case, but the more time I spent the more I convinced I became that cc65 is doing things the correct way.

So I'm sad that there is no single syntax that all major cross-assemblers accept, but I think the world would be a better place if the other assemblers changed to follow the block move syntax cc65 has adopted, rather than the other way around.
