### ISSUE TITLE
[tgi][lynx] Extra character displayed by "tgi_outtextxy"

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [cc65/cc65#955]
`tgi_outtextxy()` prints an extra blank character after each string.

Problem only verified on the Atari Lynx under emulation (Handy 0.95) with the following code:
```c
#include "display_macros.h"
#include "graphics_settings.h"
#include <tgi.h>
#define CLI() asm("\tcli")
#define _BG_COLOR TGI_COLOR_GREY
int main(void)
{
    tgi_install (tgi_static_stddrv);
    tgi_init ();		
    CLI();
    while (tgi_busy())  {  };
    tgi_setpalette(tgi_getdefpalette());
    tgi_setbgcolor(_BG_COLOR);
    tgi_setcolor(TGI_COLOR_RED);
    tgi_outtextxy(8*6,8,"hello");   
    tgi_setcolor(TGI_COLOR_WHITE);
    tgi_outtextxy(8,8,"hello"); 
    while(1){};
    return 0;
}
```
See attached an image to see the problem.

![image](https://user-images.githubusercontent.com/29057615/66563402-fe278700-eb5d-11e9-8341-8ea73347ec75.png)

**Comment by Fabrizio-Caruso** [comment]
@greg-king5  honestly this seems to me like a real bug because if you print a 10-character string, you do not expect to print 11 characters.

**Comment by greg-king5** [comment]
It has been a long time since I worked with the Lynx.  But, I think that the space is a consequence of the way that sprites are encoded.
https://github.com/cc65/cc65/blob/master/libsrc/lynx/tgi/lynx-160-102-16.s#L106-L108
The "fill-byte" always is `%11111111`, and is required as a terminator for the bit patterns (kind of like the stop bit in RS-232).  Unfortunately, it also is drawn on the screen (a hardware design flaw)!  I think that it can't be avoided.

**Comment by greg-king5** [comment]
I don't remember -- exactly -- where I got the info about Lynx programming.  I think that it was on [the AtariAge site](https://www.atariage.com/).

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 I can't believe what you have written. I cannot believe sprites are displayed with garbage at their right. This is simply impossible. The last character could be made transparent at least.

**Comment by polluks** [comment]
Indeed, maybe a hint in the doc?

**Comment by polluks** [comment]
FYI http://www.monlynx.de/lynx/sprite.html

**Comment by polluks** [comment]
FYI http://www.monlynx.de/lynx/lynx6.html

**Comment by Fabrizio-Caruso** [comment]
@greg-king5  one solution could be to use a transparency for the trailing part if there is really no way to avoid it. I have opened an issue on black vs transparency: black is seen as transparent if used as background color

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 @oliverschmidt are TGI API's supposed to behave differently from the very same TGI API's in other targets. If this is not the case than this is an issue (as well as probably #956 ).

This very issue is fixable even if a printed string has to terminate with an extra visible character by using an extra transparent color: 
- We would need to use BBP_2 instead of BBP_1 (https://github.com/cc65/cc65/blob/master/include/_suzy.h) for SPRCTL0  (=$FC80) and
- We either need a routine to convert fonts into 2 bit per pixel format or using different and twice as big font definitions.

**Comment by greg-king5** [comment]
> FYI, http://www.monlynx.de/lynx/lynx6.html

http://www.monlynx.de/lynx/lynx6.html#_64

Thanks for the link.  It refreshes my very weak memory.  This issue isn't about the sprite's encoding; it's about a hardware bug that needs an encoding work-around.  The way that the graphic chip's designer wrote about the bug makes me wonder where it is.  Maybe it's at only the right edge of the LCD (instead of the right edge of the sprite).

I will change the driver to not use the fill-byte.  I can't test that change trully, because I don't have an actual Lynx; and, I don't know how well the emulators reproduce the bug.

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 I may ask a friend to test on real hardware. He is usually available.

**Comment by Fabrizio-Caruso** [comment]
@Philsan69 could help us. He has a real Atari Lynx and whatever is needed to load a binary.

**Comment by greg-king5** [comment]
Fixed by commit f3f15cfd25dc5379ca48021884f4b96471dd895e.

**Comment by Fabrizio-Caruso** [comment]
Tested OK with Cross Chase under both Handy 0.95 
by me  and under REAL hardware by @Philsan69

![72698340_10221078216328820_4634675848786477056_o](https://user-images.githubusercontent.com/29057615/66701356-da01ac80-ecfb-11e9-8539-d348f1349dbf.jpg)

![72131050_10221078215608802_2722319652830052352_o](https://user-images.githubusercontent.com/29057615/66701355-d0784480-ecfb-11e9-8d84-415ee3916e65.jpg)

**Comment by Fabrizio-Caruso** [comment]
@greg-king5 Thanks a lot for the fix!
